### ISSUE TITLE
support for python 3.5, 3.6

### ISSUE THREAD

**Issue by siming85** [CiscoTestAutomation/pyats#1]
add support for python 3.5 and 3.6 in PyPI

**Comment by nkaliape** [comment]
Is this same limitation? (or) some new issue?
Kindly let me know if there workaround.

(pyats) nkaliape@narayan-vm:~/pyats$ python3 -V
Python 3.5.2
(pyats) nkaliape@narayan-vm:~/pyats$ pip install pyats
Collecting pyats
  Could not find a version that satisfies the requirement pyats (from versions: )
No matching distribution found for pyats
(pyats) nkaliape@narayan-vm:~/pyats$ cat /etc/issue
Ubuntu 16.04.3 LTS \n \l

**Comment by siming85** [comment]
yep, same problem. Please use python 3.4
on ubuntu it goes:

`apt-get install python3.4 python3.4-pip python3.4-venv`

then:

`python3.4 -m venv <folder>`' to create a virtual environment.

**Comment by siming85** [comment]
support for python 35/36 is added in v4.1.+
