### ISSUE TITLE
pyats logs view 21.5 opens default archive & runinfo path always

### ISSUE THREAD

**Issue by naciohr** [CiscoTestAutomation/pyats#104]
Hello Cisco.

I am having some issues to open **pyats logs view** in a custom folder. I'm working with a virtual python environment in a custom local scope.

I added log and easypy configuration in **pyats.conf**
```
[logs]
server.host = <my localhost>
server.port = 50000
browser = /usr/bin/firefox

[easypy]
runinfo.archive = /home/myuser/pyATS/archive
runinfo.directory = /home/myuser/pyATS/runinfo
```
So when I run the jobs now as ```pyats run job myjob``` the report is archived in *archive* and the temp live files are stored correctly in *runinfo*.

Now, when I run ```pyats logs view /home/myuser/pyATS/archive``` it opens the server with all the jobs stored previously in the default path at /home/myuser/.pyats/archive and the latest job shows up as errored.

In addition, if I specify ```pyats logs view /home/myuser/pyATS/archive/myLastJob.zip``` it opens the report correctly and also the jobs stored in the default path.

![imaxe](https://user-images.githubusercontent.com/38810239/121150809-217b6b80-c844-11eb-95c2-046e6e064887.png)

I would like to know whether this is actually expected plus whether there is a way to change the default path ```pyats logs view``` opens the list of jobs. I understand it uses the default path when no configuration is specified, but this causes mixing results of different projects.

Should you need further details don't hesitate to enquire.

Thanks and regards.

**Comment by LukasMcClelland** [comment]
Hi @naciohr 

Currently specifying the archive list location is not supported but it is in the backlog and we intend to add in this functionality in the future.

What you've described is the correct current behavior. For now, continue to specify the `.zip` file you wish to open in log viewer.

> plus whether there is a way to change the default path pyats logs view opens the list of jobs

Currently, it's hard-coded but there will be a fix for it in the future.

Thanks,
Lukas

**Comment by LukasMcClelland** [comment]
I just spoke with a colleague and the ability to pass in a custom directory should be included in the next release :)

**Comment by naciohr** [comment]
Dear Lukas.

Many thanks for the information. I'll be looking forward to it.

Regards.
