### ISSUE TITLE
Error importing pyats library in django view

### ISSUE THREAD

**Issue by ariandres** [CiscoTestAutomation/pyats#120]
Hi,

When importing the pyats library `from pyats.topology.loader import load` in django view, the following error occurs
I attach the code [code.zip](https://github.com/CiscoTestAutomation/pyats/files/6887819/code.zip)
django = 3.2.5
pyats = {extras = ["full"], version = "==21.6"}

views.py
from django.http import HttpResponse
from pyats.topology.loader import load

def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

web_1          | Traceback (most recent call last):
web_1          |   File "/usr/src/app/manage.py", line 22, in <module>
web_1          |     main()
web_1          |   File "/usr/src/app/manage.py", line 18, in main
web_1          |     execute_from_command_line(sys.argv)
web_1          |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
web_1          |     utility.execute()
web_1          |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
web_1          |     self.fetch_command(subcommand).run_from_argv(self.argv)
web_1          |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
web_1          |     self.execute(*args, **cmd_options)
web_1          |   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 61, in execute
web_1          |     super().execute(*args, **options)
web_1          |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
web_1          |     output = self.handle(*args, **options)
web_1          |   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 96, in handle
web_1          |     self.run(**options)
web_1          |   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 103, in run
web_1          |     autoreload.run_with_reloader(self.inner_run, **options)
web_1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 638, in run_with_reloader
web_1          |     start_django(reloader, main_func, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 623, in start_django
web_1          |     reloader.run(django_main_thread)
web_1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 329, in run
web_1          |     self.run_loop()
web_1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 335, in run_loop
web_1          |     next(ticker)
web_1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 375, in tick
web_1          |     for filepath, mtime in self.snapshot_files():
web_1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 391, in snapshot_files
web_1          |     for file in self.watched_files():
web_1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 289, in watched_files
web_1          |     yield from iter_all_python_module_files()
web_1          |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 116, in iter_all_python_module_files
web_1          |     return iter_modules_and_files(modules, frozenset(_error_files))
web_1          | TypeError: unhashable type: 'Configuration'

Thanks for the help

**Comment by domachad** [comment]
Hi @ariandres,
I have a few questions just to cover all our bases:
Are you sure that pyats is installed and working in the environment that you are using? 
Does it work when you comment out the import?
Did you try importing any other modules from pyats?

**Comment by ariandres** [comment]
Hi @domachad,
Yes, pyats is installed it works in the environment, in the attached code I also attached the files Pipfile and Pipfile.lock in case they help to find the problem. I am using pipenv.
After Comment out the import I have to restart the server with the command "python manage.py runserver 0:8001" and it works.
I have tried with the following modules and they all produce the same error inside a django project, on the outside they work without problem.
from pyats.topology.loader import load
from pyats.log.utils import banner
from genie.testbed import load
from genie.utils.diff import Diff
from genie.metaparser import MetaParser
from genie.metaparser.util.schemaengine import Any, Or, Optional
from genie import parsergen

**Comment by domachad** [comment]
Hi @ariandres,
Since your pyATS installation is working, it seems to be a problem with how you are importing external libraries into Django.
By doing a quick search on the internet, I found examples of users facing similar issues with other libraries.
For example, here is one:
https://stackoverflow.com/questions/58768309/django-cant-import-external-libraries

**Comment by ariandres** [comment]
Hi @domachad,
I do not think I am doing anything wrong, I have used many libraries in django without problem, the error of this user is that Django cannot find the module to import it, in mine it seems that pyats conflicts with Django

**Comment by domachad** [comment]
Hi @ariandres,

I'm sorry, you're correct. That link was for a different same issue.
But this one is: https://github.com/ktbyers/netmiko/issues/1955

There seems to be a problem when Django is looking for libraries in site-packages, but as previously stated, this is not a problem with pyATS. In this issue, the user seemed to find a way around it. Perhaps it will work for you as well.

**Comment by sogloarcadius** [comment]
Hello @domachad @ariandres ,

This issue is related to the django development built in web server which load and cache the modules using the decorator `lru_cache`
https://docs.python.org/3/library/functools.html#functools.lru_cache

This decorator is used in the function `iter_modules_and_files`  in the file /usr/local/lib/python3.9/site-packages/django/utils/autoreload.py" at  line ~ 119

This decorator works only on hashable objects but when you import pyats in a django application, the `sys.modules` contains the following entry `[..., Configuration({}), ....]` which break the django function `iter_modules_and_files` because it is a call to the class pyats.datastructures.configuration.Configuration which is an unhashable class. 

A workaround, would be to make a simple change to the function `iter_all_python_module_files` at line 116 of the file `/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py`

The original function 

```python
def iter_all_python_module_files():
    # This is a hot path during reloading. Create a stable sorted list of
    # modules based on the module name and pass it to iter_modules_and_files().
    # This ensures cached results are returned in the usual case that modules
    # aren't loaded on the fly.
    keys = sorted(sys.modules)
    modules = tuple(m for m in map(sys.modules.__getitem__, keys) if not isinstance(m, weakref.ProxyTypes))
    return iter_modules_and_files(modules, frozenset(_error_files))
```

The patched function (Idea : make sure modules tuple contains only hashable objects

```python
def iter_all_python_module_files():
    # This is a hot path during reloading. Create a stable sorted list of
    # modules based on the module name and pass it to iter_modules_and_files().
    # This ensures cached results are returned in the usual case that modules
    # aren't loaded on the fly.
    from collections.abc import Hashable 
    keys = sorted(sys.modules)
    modules = tuple( m for m in map(sys.modules.__getitem__, keys) if ( (not isinstance(m, weakref.ProxyTypes)) and isinstance(m, Hashable) ) )
    return iter_modules_and_files(modules, frozenset(_error_files))
```

Would be great, if the PyATS developpers get in touch with DJANGO developpers to solve this issue, I am sure other people will try to integrate pyats in their django application

Regards,

**Comment by ariandres** [comment]
Hi @sogloarcadius,

Great answer, it is a very difficult error to debug.

Thank you.

**Comment by domachad** [comment]
@sogloarcadius

Thank you for your contribution. This is very helpful.
I agree with you and I will pass the idea along to my manager

I will close the issue for now, but we will continue working on it.
Thanks once again

**Comment by petersmiddy** [comment]
@domachad , we are running into this issue, and the workaround as noted by @sogloarcadius works for us, but we can't go to production like this.  Has there been any further progress made with regards to fixing this in the iter_all_python_module_files function ?  Thanks.

**Comment by petersmiddy** [comment]
@domachad - we noticed this is still an issue even when running the latest Django version 4.0.3, has there been any progress made?

**Comment by domachad** [comment]
@petersmiddy this is something that needs to be solved by Django's development team. It is outside our control.
You can open a ticket here https://code.djangoproject.com/query
