### ISSUE TITLE
Let `ssh` resolve hostname to leverage user's configuration

### ISSUE THREAD

**Issue by vincentbernat** [CiscoTestAutomation/pyats#125]
Hey!

In my `~/.ssh/config`, I have the appropriate `ProxyJump` instructions to reach a router. They are unfortunately ignored as the hostnames put as IP in the testbed YAML file are solved to IP before being provided to SSH. It would be nice to let SSH do the resolution for this reason. I think it applies to most connection types.

**Comment by LukasMcClelland** [comment]
Hi Vincent, thanks for reaching out! I'll bring it up with the team to discuss and add it to the backlog 👍
