### ISSUE TITLE
 Please fix some other pylint errors

### ISSUE THREAD

**Issue by extsoft** [CiscoTestAutomation/pyats#13]
After 5.0.0 pyATS release, some pylint's violations disappear (described in #8). But some of them still exist. Please solve them if possible.

Errors:
- E1101: Module 'pyats.topology.loader' has no 'load' member (no-member)
- E0611: No name 'SubCommandFailure' in module 'unicon.core.errors' (no-name-in-module)
- Module 'pyats.easypy' has no 'run' member (no-member)

Versions:
- `pyats==5.0.1`
- `unicon==3.4.0`
- `pylint==2.1.1`

**Comment by tahigash** [comment]
Hi @extsoft sorry for delayed response. what code did you use to see those errors? Please provide because I will check the code with latest packages.

**Comment by extsoft** [comment]
@tahigash please check this code

```python
from ats.topology import loader
cluster = loader.load('./testbeds/test.yaml')
```

**Comment by tahigash** [comment]
@extsoft thanks for your reply. I tried with latest packages.
(changed from `from ats` to `from pyats`)

```
$ cat test.py
from pyats.topology import loader
cluster = loader.load('./testbeds/test.yaml')
```

I see only below one and don't see the same with latest. Can we close this issue?
```
pylint test.py
************* Module test
test.py:1:0: C0114: Missing module docstring (missing-module-docstring)

------------------------------------------------------------------
Your code has been rated at 5.00/10 (previous run: 5.00/10, +0.00)
```
```
$ pip freeze | egrep 'ats|pylint'
pyats==20.8
pyats.aereport==20.8
pyats.aetest==20.8
pyats.async==20.8
pyats.connections==20.8
pyats.contrib==20.8
pyats.datastructures==20.8
pyats.easypy==20.8
pyats.kleenex==20.8.1
pyats.log==20.8
pyats.reporter==20.8
pyats.results==20.8
pyats.robot==20.8
pyats.tcl==20.8
pyats.topology==20.8
pyats.utils==20.8
pylint==2.6.0

**Comment by extsoft** [comment]
@tahigash Looks like it works now. Close the issue.
