### ISSUE TITLE
pyats logs view 21.8 does not update new archived jobs

### ISSUE THREAD

**Issue by naciohr** [CiscoTestAutomation/pyats#130]
Hello Cisco,

I have a server running pyats logs view in a specific archive folder - specified by pyats.conf - and I detected the following:

- When I start the logs viewer it opens a fake last job flagged as errored.
- When I run new jobs, the viewer does not update with the new results and I have to restart the viewer.

I tried with option **keepalive** but the result is the same.

May you tell if this behaviour is expected, please? If that's the case, how can I leave the viewer "as a service" updating new jobs results?

Thanks and regards.

**Comment by LukasMcClelland** [comment]
Hi @naciohr,  

> When I start the logs viewer it opens a fake last job flagged as errored.

I've tried to reproduce this error but specifying an archive directory in a pyats.conf file and then running `pyats live view` works correctly on my end, What version of pyATS do you have? (you can check with `pip list`). If it's not 21.8, then please update pyATS and related packages.

> When I run new jobs, the viewer does not update with the new results and I have to restart the viewer.

Please try using the --liveview option. 

Docs on usage can be found here https://pubhub.devnetcloud.com/media/pyats/docs/cli/pyats_logs.html#pyats-logs-view

**Comment by naciohr** [comment]
Hello @LukasMcClelland 

Many thanks for your reply. Apologies because I didn't provide enough details so you can do proper tests.

**Base setup**
- Setup pyats.conf. This line should make pyats logs view look for archive directory in the same path where the command is run.
`server.host = 0.0.0.0`
`server.port = 9002`
`runinfo.archive = archive`

**Test 1**
- Started **pyats logs view** in the same parent folder as archive.
- **pyats run job jobs/myjob.py**

_Expected result:_

1.  Pyats logs view web shows the last jobs in the folder with no errored job.
2. Pyats logs view web shows the last job after refresh.

_Actual result:_

1. Correct.
2. Not showing the latest job. The command needs to re-issue to show the jobs run later.

After running the job and refresh web:
![imaxe](https://user-images.githubusercontent.com/38810239/134881983-f7c753b4-7e1b-4cec-a2ad-ad1ded93527f.png)

After re-issuing **pyats logs view**:
![imaxe](https://user-images.githubusercontent.com/38810239/134882480-33495dcf-62c3-4d84-a6ba-43f77a4c9013.png)


**Test 2**
- Started **pyats logs view --liveview** in the same parent folder as archive.
- **pyats run job jobs/myjob.py**

_Expected result:_

1. Pyats logs view web shows the last jobs in the folder with no errored job.
2. Pyats logs view web shows the last job after refresh.

_Actual result:_

- Web not loading.
- Error:
![imaxe](https://user-images.githubusercontent.com/38810239/134883217-1bf79a96-cc26-478f-a336-010223528684.png)

So, back to my initial report:

> When I start the logs viewer it opens a fake last job flagged as errored. [SOLVED]

> When I run new jobs, the viewer does not update with the new results and I have to restart the viewer.[PERSISTENT]

Thanks and regards

**Comment by LukasMcClelland** [comment]
@naciohr Thank you for the info! I'll investigate today

**Comment by LukasMcClelland** [comment]
I found this in [our changelogs for April 2020](https://pubhub.devnetcloud.com/media/pyats/docs/changelog/2020/apr.html) `User can either use ‘pyats run job job.py --liveview’ to enable liveview when starting a job, or use command ‘pyats logs view --liveview’ anytime when a job is running`

Please try adding `--liveview` to `pyats run job` 
https://pubhub.devnetcloud.com/media/pyats/docs/cli/pyats_run.html#pyats-run-job
```
Liveview:
  --liveview            Starts a liveview server in a separate process
  --liveview-host HOST  Specify host for liveview server. Default is localhost
  --liveview-port PORT  Specify port for liveview server.
  --liveview-hostname HOSTNAME
                        Displayed hostname for liveview.
  --liveview-displayed-url LIVEVIEW_DISPLAYED_URL
                        Displayed url for liveview, for example, http://<liveview_hostname>:<port>
  --liveview-keepalive  Keep log viewer server alive after the run finishes.
  --liveview-callback-url LIVEVIEW_CALLBACK_URL
                        Specify xpresso callback url for jenkins run.
  --liveview-callback-token LIVEVIEW_CALLBACK_TOKEN
                        Specify xpresso token for jenkins run.
```

Hopefully this helps!

**Comment by naciohr** [comment]
Lukas, I believe we are drifting from the issue I reported.

I'm not reporting I can't see jobs while they run. The issue is, I can't see the result of a new job stored as archive if I had the pyats logs view running previously; i.e., the list of finished jobs in the archive folder is not being updated in the web frontend if the pyats logs view service is already running.

To force an update I need to stop pyats logs view and relaunch.

Best regards,

**Comment by LukasMcClelland** [comment]
So, I've investigated/asked around and getting updates of new jobs while the log viewer is open is not currently an available option. To get the results of the latest run, pyats log viewer must be stopped and relaunched.

We are planning to implement this but it's not a priority item.

**Comment by naciohr** [comment]
Dear Lukas,

Many thanks for the information. I'll pay attention to the new releases and I hope thus solution comes soon


Best regards.
