### ISSUE TITLE
在django中使用出错

### ISSUE THREAD

**Issue by linjiawang** [CiscoTestAutomation/pyats#137]
当我安装pyats后，在我的django项目中导入netmiko时报错
django似乎会对安装的模块进行遍历，在这个阶段报错了。

还有当我导入nornir并允许InitNornir时也会出现和上述一样的错误，然而单单导入nornir并不会出现该种错误。

当我卸载pyats后，nornir和netmiko运行正常
django==3.2.9
netmiko==3.4.0
pyats == 21.10
nornir==3.1.1

希望得到答复关于此问题的解决方法，亦或关于django运行netmiko，nornir，pyats模块同时运行的方式

**Comment by lsheikal** [comment]
Hi @linjiawang,
Kindly create a new issue in English. Closing this ticket now.
