### ISSUE TITLE
show dmvnp crashed if HNRP type is Unknown

### ISSUE THREAD

**Issue by uid2021** [CiscoTestAutomation/pyats#139]
The output of 'show dmvpn' looks like this:
-- snippet start --
Interface: Tunnel2238, IPv4 NHRP Details
Type:Unknown, NHRP Peers:1, 
        
  Ent  Peer NBMA Addr Peer Tunnel Add State  UpDn Tm Attrb
 ----- --------------- --------------- ----- -------- -----
     1 UNKNOWN           172.28.172.30  NHRP    never    IX
-- snippet end --

pyats crashed with this error message:
The pyats library return an error for 'show dmvpn' for 'iosxe'. Error: Missing keys: [['interfaces', 'Tunnel2238', 'ent']].

pyats should either ignore this interface or use UNKNOWN as the Type and continue to parse other valid interfaces.

**Comment by GerriorL** [comment]
Hi uid2021,

Thank you for bringing this to our attention. A fix has been created and will be available in our next release.

**Comment by uid2021** [comment]
Thank you very much for your prompt action. I look forward to your new release.
