### ISSUE TITLE
Cannot create testbed in interactive mode

### ISSUE THREAD

**Issue by parrywangyin** [CiscoTestAutomation/pyats#156]
I'm an absolute beginner of pyats. I installed pyats through **pip install 'pyats[full]'**

I was trying to create the testbed in interactive mode (**genie create testbed interactive --output testbed1.yml**), but always got below error:

```
 [root@localhost pyats]# genie create testbed interactive --output testbed1.yml

please make sure pyats.contrib is installed. If not, please do 'pip install pyats.contrib'.

invalid option: interactive

```

I'm pretty sure that pyats.contrib is installed with version 22.3:

```
 [root@localhost pyats]# pip freeze | grep pyats.contrib
pyats.contrib==22.3

```

And I did '**pyats version update**' as well, but still no luck.

What should I do?

**Comment by domachad** [comment]
Can you please run `pip list | egrep "ats|genie|unicon"` and share the output?

**Comment by parrywangyin** [comment]
> Can you please run `pip list | egrep "ats|genie|unicon"` and share the output?

Hi Domachad,

```
[root@localhost ~]# pip list | egrep "ats|genie|unicon"
genie                        21.3.1
genie.libs.clean             21.3
genie.libs.conf              21.3
genie.libs.filetransferutils 21.3
genie.libs.health            21.3
genie.libs.ops               21.3
genie.libs.parser            21.3
genie.libs.sdk               21.3
pyats                        21.3
pyats.aereport               21.3
pyats.aetest                 21.3.1
pyats.async                  21.3
pyats.connections            21.3
pyats.datastructures         21.3
pyats.easypy                 21.3
pyats.kleenex                21.3
pyats.log                    21.3.1
pyats.reporter               21.3
pyats.results                21.3
pyats.tcl                    21.3
pyats.topology               21.3
pyats.utils                  21.3
unicon                       21.3
unicon.plugins               21.3
```

**Comment by domachad** [comment]
I don't see `pyats.contrib` in this list. Are you sure you have it installed?

**Comment by parrywangyin** [comment]
> 

Thank you domachad. My bad, I forgot that I previously installed pyats in a virtual environment, the output of **pip list | egrep "ats|genie|unicon"** is not from that venv, issued solved after I activate the venv.
