### ISSUE TITLE
Add Linux ARM64 to build process

### ISSUE THREAD

**Issue by qzx** [CiscoTestAutomation/pyats#158]
With the current version 22.3 we've got builds on [pypi](https://pypi.org/project/pyats/#files) for:

linux x86_64
macosx x86_64
macosx arm64

but there is no build for **linux arm64**.

The reason I mention the arm64 linux build is due to the upcoming DevNet Expert exam, which will be taken on a Ubuntu image with certain software installed. In order to run a copy of this VM on a M1 MacBook, we need arm64 support.

It's possible to install almost all of the software listed by Cisco for this VM, the main hold-out for it to be a really functioning training VM is pyATS not existing for the platform, which also prevents installation of genie.

Would it be possible to add this Operating System and Architecture combination to the build pipeline?

**Comment by danielgraziano** [comment]
Unfortunately at this time we are not planning to add linux arm64 builds. You can use docker as an alternative as we build docker images. We may revisit this in the future.

https://hub.docker.com/r/ciscotestautomation/pyats/
