### ISSUE TITLE
Pyats excel testbed 

### ISSUE THREAD

**Issue by g-arjuna** [CiscoTestAutomation/pyats#159]
When creating testbed yaml files from Excel sheet the username column keyed in Excel gets converted to float if the username contains all numbers . 

Example if username is 12345 then generated yaml file contains username 12345.0 in float

**Comment by sjpatel21** [comment]
Hi,

Excel stores numbers as float internally, and so when the file is read, the numbers are converted to float as you saw.
A simple workaround for this is that you convert the excel file to csv file and use it to create yaml file.

Please give it a try and let me know if it works.
