### ISSUE TITLE
Where is TopologyGrapher now?

### ISSUE THREAD

**Issue by supertylerc** [CiscoTestAutomation/pyats#17]
What happened to `ats.topology.grapher.TopologyGrapher`?  There are some docs that aren't linked from the current docs, but they're still available at `/latest` if you go looking (though the page indicates it's for `4.0.1`).  The page for [TopologyGrapher is here](https://pubhub.devnetcloud.com/media/pyats/docs/topology/grapher.html), but I can't find it referenced in the `5.0.x` documentation, and `dir(ats.topology)` doesn't have `grapher` listed:

```
Python 3.6.7 (default, Nov 27 2018, 20:59:50) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pyats.topology.grapher
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-5ba41f10988a> in <module>
----> 1 import pyats.topology.grapher

ModuleNotFoundError: No module named 'pyats.topology.grapher'

In [2]: import pyats.topology

In [3]: dir(pyats.topology)
Out[3]: 
['Device',
 'DeviceBase',
 'Interface',
 'InterfaceBase',
 'Link',
 'LinkBase',
 'Testbed',
 'TestbedBase',
 '__author__',
 '__builtins__',
 '__cached__',
 '__contact__',
 '__copyright__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'bases',
 'device',
 'exceptions',
 'interface',
 'link',
 'loader',
 'schema',
 'testbed']

In [4]:
```

Was it completely removed in `5.0.x`?  Is there an alternative, or is this functionality that I need to go build myself?

Thanks!

**Comment by siming85** [comment]
Apologies for the delay! the team had a long christmas holiday break :)

TopoGrapher used to be a built-in package into pyATS, but it had deep dependencies on system packages to be present (so it could generate PDF/graphs). For that, we removed it from built-in to be optional package instead. It looks like we didn't remove the documentation for it.

right now this optional package isn't released, but if that's something you're interested in, the team needs to internally discuss it. 

Meanwhile, we'll update the documentation to reflect so

**Comment by ThomasJRyan** [comment]
In case anyone else comes across this, `topology.grapher` has been fully deprecated and is not receiving any further support
