### ISSUE TITLE
Support Python3.10

### ISSUE THREAD

**Issue by jvanderaa** [CiscoTestAutomation/pyats#174]
This is the real issue that was at hand compared to the previous ARM issue reported. It is a Python3.10 support issue. The places on i386 where individuals trying to install pyATS are getting errors. The errors are seen on an Ubuntu 22.04 machine that has Python3.10.

I would propose adding Python3.10 to the setup, but am unable to do a PR against the library to do so (and run the test suite against it).

**Comment by sjpatel21** [comment]
Hello,
Ideally python 3.10 should be compatible with pyATS, but if you are facing any specific issues or errors, we will be happy to take a look.

Thank you
