### ISSUE TITLE
pyats apple silicon docker linux pip fails to install 

### ISSUE THREAD

**Issue by gophry** [CiscoTestAutomation/pyats#182]
### Setup Details
OS Name: macOS Monterey
OS Version: 12.5.1
Docker Desktop: 4.9.0 (80466)
Docker Engine: v20.10.16

Guest OS: Debian GNU/Linux 11 (bullseye)
python version 3.9.14
pip version 22.2.2

### Observation
* pypi packages list has arm64 wheel files for only MacOS. so pip doesn't find a compatible version for linux with arm64

**Comment by Taarini** [comment]
Hi 

Currently we don't support arm64. 
But you can use a docker container to run pyats by following the below documentation link, https://hub.docker.com/r/ciscotestautomation/pyats/
