### ISSUE TITLE
when it will adapt with python3.11

### ISSUE THREAD

**Issue by markict** [CiscoTestAutomation/pyats#187]
looking forward to adapting with python3.11

**Comment by simingy** [comment]
+1

**Comment by sjpatel21** [comment]
Hi, are you looking at some specific features of python 3.11 ?

**Comment by markict** [comment]
> Hi, are you looking at some specific features of python 3.11 ?

I often deal with device log by python, for this kind of tasks, I noticed that there is a huge performance improvement on python3.11.  but unfortunately, as one of the important part, the PyATS doesn't support python3.11 yet.    so I have to collect logs by PyATS on python3.10.  and parsing logs on python3.11.

**Comment by sjpatel21** [comment]
Noted, we should be moving to 3.11 in the next few months. Though there is no strict timeline set.
