### ISSUE TITLE
Support for aarch64 linux

### ISSUE THREAD

**Issue by goshuto** [CiscoTestAutomation/pyats#192]
Cannot install on aarch64 linux (ubuntu).

Add support for aarch64 architecture as a lot of people are running virtual machines on M1/M2 Macs.

**Comment by ademz** [comment]
Hello,

We are not supporting `aarch64` yet. But this is in our backlog, we will implement it in the future. 

Thank you,
Adem Oztas

**Comment by goshuto** [comment]
Thanks Adem, I hope it will be implemented soon.
