### ISSUE TITLE
Missing Python3.11 pyats and genie wheel files.

### ISSUE THREAD

**Issue by ktbyers** [CiscoTestAutomation/pyats#195]

**Comment by Taarini** [comment]
Hi

Can you elaborate on what is missing

**Comment by ktbyers** [comment]
There are no Python 3.11 wheel files.

https://pypi.org/project/pyats/#files

Or worded differently, try to use either Pyats and/or Genie on Python3.11 (where you install from pypi)--this will fail.

**Comment by Taarini** [comment]
Hi

We are working on it and planned to release it on January 2023

**Comment by ktbyers** [comment]
Any update on this? I just checked the January release and missing Python 3.11 wheel files. This causes my CI-CD environment for Netmiko to break (if I try to test on PY3.11).

@Taarini

**Comment by Taarini** [comment]
We are working on it and let you know once it is released.

**Comment by ktbyers** [comment]
@Taarini Python 3.11 has been out for about 8 months now and Cisco pyats/genie support on it is still broken. 

Any way to get this fixed?

**Comment by ktbyers** [comment]
@bastell Any possibility we can get this working? It looks entirely like a release process issue (i.e. not creating the needed files for PY3.11 support).

FWIW, this also breaks my testing on Netmiko (i.e. I have to disable PY3.11 testing due to the pyats/genie lack of PY3.11 support).

**Comment by ktbyers** [comment]
This was fixed in pyats 23.7 release.

**Comment by MrPaulAR** [comment]
Too early to request 3.12 :P

**Comment by ktbyers** [comment]
@MrPaulAR I did think that also... :-)
