### ISSUE TITLE
Couldn't install pyats[full] 23.6/23.5 with poetry

### ISSUE THREAD

**Issue by seisokeii** [CiscoTestAutomation/pyats#215]
Use poetry to install pyats[full] will fail because of package dependencies. This happen when I try to install 23.5 version and latest 23.6.

error message is :
`Invalid requirement (backports.ssl (>=0.0.9backports.ssl-match-hostname>=3.5.0.1)) found in ixnetwork-9.0.1915.16 dependencies, skipping`

I cannot control backports.ssl and  backports.ssl-match-hostname version.

**Comment by seisokeii** [comment]
This error cause by pyats-datastructures (23.6)

```
$poetry show pyats-datastructures
 name         : pyats-datastructures                                       
 version      : 23.6                                                       
 description  : pyATS Datastructures: Extended Datastructures for Grownups 

required by
 - pyats >=23.6.0,<23.7.0
 - pyats-aetest >=23.6.0,<23.7.0
 - pyats-connections >=23.6.0,<23.7.0
 - pyats-easypy >=23.6.0,<23.7.0
 - pyats-kleenex >=23.6.0,<23.7.0
 - pyats-log >=23.6.0,<23.7.0
 - pyats-tcl >=23.6.0,<23.7.0
 - pyats-topology >=23.6.0,<23.7.0
 - pyats-utils >=23.6.0,<23.7.0
```
This error relate to ixnetwork package
```
Source (PyPI): 5 packages found for ixnetwork *
Invalid requirement (backports.ssl (>=0.0.9backports.ssl-match-hostname>=3.5.0.1)) found in ixnetwork-9.0.1915.16 dependencies, skipping
   1: fact: ixnetwork (9.0.1915.16) depends on pyopenssl (>=17.5.0)
   1: fact: ixnetwork (9.0.1915.16) depends on requests (>=2.18.4)
   1: fact: ixnetwork (9.0.1915.16) depends on websocket-client (>=0.47.0)
   1: selecting ixnetwork (9.0.1915.16)
   1: derived: websocket-client (>=0.47.0)
   1: derived: pyopenssl (>=17.5.0)

```

**Comment by seisokeii** [comment]
I've created a new repo then first install pyats[full] and it works...
The package pyats-datastructures is successful installed but the error message is still there.
```
Invalid requirement (backports.ssl (>=0.0.9backports.ssl-match-hostname>=3.5.0.1)) found in ixnetwork-9.0.1915.16 dependencies, skipping
```

I don't know what wrong...

**Comment by ParimiNeeraja** [comment]
Hi seisokeii,

After installing the pyats using `/auto/pyats/bin/pyats install`  this command, can you try to upgrade using `pip install --upgrade "ats[full]"` . It will help to resolve your issue..

**Comment by seisokeii** [comment]
Sorry, I forget to say that I use poetry to install pyATS. 

pyATS is work fine now, but there's a dependency warning when execute python script.
 ``` NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3' ```

 I think this is not a critical problem.
 
Thank for your help~

**Comment by ParimiNeeraja** [comment]
This issue does not appear on virtual environments based on python binaries built with openssl. If you want to avoid this error make sure your python binary is built with openssl, or downgrade urllib to a version that supports libressl

**Comment by seisokeii** [comment]
This issue is solved.  I appreciate your help~
