### ISSUE TITLE
No pyats.datastructures 23.11 wheels available for MacOS

### ISSUE THREAD

**Issue by jillesca** [CiscoTestAutomation/pyats#227]
I tried to install pyats[full] with Poetry, however it failed due to no available wheels for `pyats.datastructures` for 23.11.

`pyats.datastructures` 23.10 has available wheels for MacOS, and I was able to install pyats using this specific version `poetry add "pyats[full]"==23.10`

From this issue raised with Poetry https://github.com/python-poetry/poetry/issues/4565 it seems the `pyats.datastructures` wheels are a recurring issue. 

Currently, there are only `pyats.datastructures` 23.11 wheels for linux 
![image](https://github.com/CiscoTestAutomation/pyats/assets/76405615/ae585455-b9ca-4439-9cde-217d611ce028)

While `pyats.datastructures` 23.10 has wheels for more platforms.
![image](https://github.com/CiscoTestAutomation/pyats/assets/76405615/2027a45e-ffdc-4d47-a723-71cc77459b63)

Could it be possible to automate the built for `pyats.datastructures` so there are always wheel for all platforms at the time of new releases?

**Comment by SohanTirpude** [comment]
Hello @jillesca,

Kindly give me some time to check with the team on this. I will get back to you as soon as possible. 

Thank you.

**Comment by SohanTirpude** [comment]
Hello @jillesca,

The team has added all necessary wheel files for MacOS, kindly check again and let me know. Meanwhile, I am closing this issue, if you still face the issue then kindly re-open the ticket.

Thank you.
