### ISSUE TITLE
Login fails when the device hostname differs from testbed file

### ISSUE THREAD

**Issue by renatoalmeidaoliveira** [CiscoTestAutomation/pyats#24]
When the device hostname differs greatly from the device name on the testbed file the framework fails to recognize the login.
In the trace that follows its possible to see that the connection succeeds, but the library fails to recognize the login, because the regex pattern doesn't match a different hostname
Follow the error trace:

`Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyats.topology import loader
>>> testbed = loader.load('testbed.yaml')
>>> testbed.devices['R1'].connect()
[2019-06-25 19:12:54,493] +++ R1 logfile /tmp/R1-default-20190625T191254492.log +++
[2019-06-25 19:12:54,493] +++ Unicon plugin iosxe +++
Trying 10.1.1.1...

[2019-06-25 19:12:54,502] +++ connection to spawn: telnet 10.1.1.1 23, id: 140033124293880 +++
[2019-06-25 19:12:54,502] connection to R1
Connected to 10.1.1.1.
Escape character is '^]'.
C

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+                                                                           +
+                  ATTENTION: AUTHORIZED PERSONAL ONLY!                   +
+                    IF YOU ARE NOT AUTHORIZED PERSONAL                   +
+                         DISCONNECT IMMEDIATELY.                         +
+                                                                         +
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

User Access Verification

Username: ****
Password: 
C

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+                                                                         +
+              CONNECTED ON VTY#2 OF avocado.            +
+                                                                         +
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

avocado#Traceback (most recent call last):
  File "src/unicon/statemachine/statemachine.py", line 697, in unicon.statemachine.statemachine.StateMachine.go_to
  File "src/unicon/statemachine/statetransition.py", line 479, in unicon.statemachine.statetransition.AnyStateTransition.do_transitions
  File "src/unicon/eal/dialogs.py", line 419, in unicon.eal.dialogs.Dialog.process
  File "src/unicon/eal/dialog_processor.py", line 660, in unicon.eal.dialog_processor.AlarmBasedDialogProcessor.process
  File "src/unicon/eal/dialog_processor.py", line 645, in unicon.eal.dialog_processor.AlarmBasedDialogProcessor.process
  File "src/unicon/eal/dialog_processor.py", line 547, in unicon.eal.dialog_processor.AlarmBasedDialogProcessor.expect_eval_statements
  File "src/unicon/eal/backend/pty_backend.py", line 153, in unicon.eal.backend.pty_backend.RawSpawn.read_update_buffer
  File "src/unicon/eal/dialog_processor.py", line 605, in unicon.eal.dialog_processor.AlarmBasedDialogProcessor.timeout_handler
unicon.core.errors.TimeoutError: timeout occurred:
                              timeout value: 60
                              last_command: '*****\r'
                             pattern: ['^.*?% (Bad passwords|Access denied|Authentication failed)', '^.*Login incorrect', '^.*([Uu]sername|[Ll]ogin): ?$', '^.*User Access Verification', '^.*[Pp]assword( for )?(\\S+)?: ?$', '^(.*)Kerberos: No default realm defined for Kerberos!', '^.*(initial|basic) configuration dialog ?\\?? ((\\[yes.*\\])|(\\(yes/no\\))|(\\(yes/no\\) (\\[y\\]))):', 'Would you like to enter basic management setup\\? \\[yes/no\\]:', 'Escape character is .*\\n', '^.*RETURN to get started', 'Are you sure you want to continue connecting \\(yes/no\\)', '^.*(Connection refused|Connection reset by peer|Network is down|closed by remote host)', 'Received disconnect from .*:', 'Hit Enter to proceed:', '^(.*?)Press Ctrl\\+x to Exit the session', '^(.*?)Connected.', '^.*[Pp]assword( for )?(\\S+)?: ?$', '^.*?% (Bad passwords|Access denied|Authentication failed)', '^.*System config(uration)? has been modified\\. Save\\?.*$', '^.*Are you sure you want to reset the system \\(y\\/n\\)\\?', '^.*Reload node \\? \\[no,yes\\]\\s?$', '^.*Proceed( with reload)?\\? *\\[confirm\\]', '^.*Press RETURN to get started.*$', '^.*User Access Verification', '^(.*)Uncommitted changes found.*?', '^.*(initial|basic) configuration dialog ?\\?? ((\\[yes.*\\])|(\\(yes/no\\))|(\\(yes/no\\) (\\[y\\]))):', '^(.*)Would you like to terminate autoinstall\\? ?\\[yes\\]: $', '^.*Do you want to reload the internal AP\\s?\\? ((\\[yes/no\\]\\??)|(\\[y/n\\]\\??)):?\\s?$', '^.*Do you want to save the configuration of the AP\\s?\\? ((\\[yes/no\\]\\??)|(\\[y/n\\]\\??)):?\\s?$', '^(.*)This command will reboot the system. \\(y\\/n\\)\\?  \\[n\\]\\s?$', '^.*Do you want to enforce secure password standard(\\?)? \\(yes\\/no\\)( \\[[yn]\\])?\\: ?', '^.*(Enter|Confirm) the password for .*admin', 'Abort( Power On)? Auto Provisioning .*:', '^.*([Uu]sername|[Ll]ogin): ?$', '^.*[Pp]assword( for )?(\\S+)?: ?$', '^.*?% (Bad passwords|Access denied|Authentication failed)', '^.*Login incorrect', '^.*([Uu]sername|[Ll]ogin): ?$', '^.*User Access Verification', '^.*[Pp]assword( for )?(\\S+)?: ?$', '^(.*)Kerberos: No default realm defined for Kerberos!', '^.*(initial|basic) configuration dialog ?\\?? ((\\[yes.*\\])|(\\(yes/no\\))|(\\(yes/no\\) (\\[y\\]))):', 'Would you like to enter basic management setup\\? \\[yes/no\\]:', 'Escape character is .*\\n', '^.*RETURN to get started', 'Are you sure you want to continue connecting \\(yes/no\\)', '^.*(Connection refused|Connection reset by peer|Network is down|closed by remote host)', 'Received disconnect from .*:', 'Hit Enter to proceed:', '^(.*?)Press Ctrl\\+x to Exit the session', '^(.*?)Connected.', '^(.*)Please reset', '^(.*)(rommon(.*))+>', '^.*(Enter|Confirm) the password for .*admin', '^.*(initial|basic) configuration dialog.*\\s?', '^(.*)Would you like to terminate autoinstall\\? ?\\[yes\\]: $', '^.*Are you sure you want to continue\\? \\[y/n\\]\\s?', '^(.*?)\\[R1.*\\]\\$\\s?$', 'rommon[\\s\\d]*>\\s?$', '^(.*)\\(.*(con|cfg|ipsec-profile)\\S*\\)#\\s?$', '^(.*?)(Router|Switch|ios|switch|R1)(\\(standby\\))?(-stby)?(\\(boot\\))?#\\s?$', '^(.*?)(Router|Switch|ios|switch|R1)(\\(standby\\))?(-stby)?(\\(boot\\))?>\\s?$', '^.*--\\s?[Mm]ore\\s?--.*']
                             buffer:'\r\nC\r\n\r\n+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\r\n+                                                                         +\r\n+              CONNECTED ON VTY#2 OF avocado.            +\r\n+                                                                         +\r\n+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\r\n\r\n\r\navocado#'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/unicon/bases/connection.py", line 526, in unicon.bases.connection.Connection.connect
  File "src/unicon/bases/routers/connection_provider.py", line 146, in unicon.bases.routers.connection_provider.BaseSingleRpConnectionProvider.connect
  File "src/unicon/bases/routers/connection_provider.py", line 169, in unicon.bases.routers.connection_provider.BaseSingleRpConnectionProvider.establish_connection
  File "src/unicon/statemachine/statemachine.py", line 700, in unicon.statemachine.statemachine.StateMachine.go_to
unicon.core.errors.StateMachineError: Failed while bringing device to "any" state

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/pyats/connections/manager.py", line 305, in pyats.connections.manager.ConnectionManager.connect
  File "src/unicon/bases/connection.py", line 532, in unicon.bases.connection.Connection.connect
unicon.core.errors.ConnectionError: failed to connect to R1
>>> 
`

**Comment by siming85** [comment]
can't say this is a bug... there's no magical way to guess the prompt. 
The absolute most exact method is to provide the right hostname so the regex can be built.

one possible solution is to pass in :
https://pubhub.devnetcloud.com/media/unicon/docs/user_guide/connection.html#

> learn_hostname: Set to True if the actual hostname set on the device differs from the hostname parameter. (Optional)

device.connect(learn_hostname=True)

but that is not always guaranteed

**Comment by renatoalmeidaoliveira** [comment]
If that is the expected behavior, I would suggest two enhancements:
1º: Add an explicit alert on the testbed documentation, that the device name MUST match the device hostname
2º: Make the learn_hostname = true a default

**Comment by siming85** [comment]
there is now additional comment in the guide highlighting this fact.

can't be default - it's an reliable process. Automation needs to know what it is connecting to. as of right now, learning hostname is still an unreliable process, and expects the device to be in good-working state. 
Unicon at least right now does some degree of rommon recovery.

**Comment by renatoalmeidaoliveira** [comment]
Great, already see it, i think there is a little typo on the text:
"much match to your device hostname in the prompt"
About the regex, it is possible some think like /\#\s*\z/ to match any hostname, maybe it could be useful.
