### ISSUE TITLE
pyats and genie 24.5 are missing x86_64.whl file for PY3.12

### ISSUE THREAD

**Issue by ktbyers** [CiscoTestAutomation/pyats#240]
Consequently pip install on PY3.12 will fail.

```
(netmiko_test) [kbyers@pylab33a VENV]$ pip install pyats==24.5 genie==24.5
ERROR: Could not find a version that satisfies the requirement pyats==24.5 (from versions: 24.2, 24.3, 24.4)
ERROR: No matching distribution found for pyats==24.5

[notice] A new release of pip is available: 23.2.1 -> 24.1
[notice] To update, run: pip install --upgrade pip
(netmiko_test) [kbyers@pylab33a VENV]$ python --version
Python 3.12.0
```

PY3.11 installation works fine (as the x86_64.whl file exists for PY3.11).

**Comment by SohanTirpude** [comment]
Hello @ktbyers,

We have just released the pyats and genie with 24.6 version. And for those versions, we have provided whl files for x86_64. Can you please check and work with it? Meanwhile, I will check with the team whether we can provide the same for version 24.5. 

Thank you.

**Comment by ktbyers** [comment]
@SohanTirpude Sounds good. I just checked pypi and see the files are there...so sounds good to me. I was mostly concerned that the latest release supported PY3.12.

Thanks, Kirk

**Comment by SohanTirpude** [comment]
Hello @ktbyers,

Thanks to let me know that you are able to work with 24.6. Anyway, I am checking with the team whether they can release the x96_64.whl file for 24.5 so if anyone wants to work with that specific version won't have any issues. I will let you know once there is an update on it.

Thank you.
