### ISSUE TITLE
Login fail when unprivileged user log in

### ISSUE THREAD

**Issue by renatoalmeidaoliveira** [CiscoTestAutomation/pyats#25]
When the user provided on the testbed haven't conf privileges the login fails, and by the execution output, I see that the framework tries to configure the device with the following output:
 
![image](https://user-images.githubusercontent.com/16046203/60225191-8f3a5280-983a-11e9-9b09-4624c6927b21.png)

Looking at the documentation i haven't found anything about the framework issuing commands without being explicit configured, ie device.configure() or device.execute().
I would like to know if it's possible to block that behavior and use the framework with an unprivileged user

**Comment by siming85** [comment]
you can do device.connet(init_config_commands=[])

or alternatively, put that under the device block in yaml:

```yaml

devices:
    mydevice:
        connections:
            vty:
                init_config_commands: []

**Comment by renatoalmeidaoliveira** [comment]
Thank you,
    There're any other configuration command that are issued without an explicit command? And if there are I would suggest a specific section on the documentation about that.
Regards

**Comment by siming85** [comment]
no - these are the only ones done on connect, required in order for the console to not have syslogs and such .

without them it mostly works, but syslogs will be mixed into output - which makes the output reliable.

we'll update documentation on this

**Comment by renatoalmeidaoliveira** [comment]
Looking at the configuration before the test execution, and i saw that there're no roolback on the commands the the connect issued, and i think that shoud be a requirement

**Comment by siming85** [comment]
rollback might not be supported on all the platforms. you can add to the init_config_command.

as well, one thing to keep in mind is that the connector is there to provide basic connectivity, not stateful keeping.
