### ISSUE TITLE
Ping in a VRF unsupported in IOS?

### ISSUE THREAD

**Issue by jesse-mcgraw** [CiscoTestAutomation/pyats#26]
unicon==19.6

Working with an older Catalyst 6500, it appears that IOS plugin does not support the "vrf" keyword.

Switching the device type to "iosxe" allows the command to succeed but I'm not sure how this may affect further interaction with the device

**Comment by difuhu** [comment]
Hi, yes, ios ping service doesn't process vrf argument currently, while iosxe ping does. We will enhance it. Thank you for pointing it out.
As a workaround, you can pass in vrf via command argument:
device.ping(addr="1.1.1.1", command="ping vrf vrf_xxx")

**Comment by difuhu** [comment]
fixed in unicon release v19.7.
