### ISSUE TITLE
AttributeError: 'AttrDict' object has no attribute 'username'

### ISSUE THREAD

**Issue by urskog84** [CiscoTestAutomation/pyats#27]
I am traying to createing my own Testbed object. I am fill following the steps in the page
https://pubhub.devnetcloud.com/media/pyats/docs/topology/creation.html#manual-creation

but when i tray to connect. i get an error

```
----> 1 device.connect()

/usr/local/lib64/python3.7/site-packages/pyats/connections/manager.cpython-37m-x86_64-linux-gnu.so in pyats.connections.manager.ConnectionManager.connect()

/usr/local/lib64/python3.7/site-packages/pyats/connections/manager.cpython-37m-x86_64-linux-gnu.so in pyats.connections.manager.ConnectionManager.instantiate()

/usr/local/lib64/python3.7/site-packages/unicon/adapters/topology.cpython-37m-x86_64-linux-gnu.so in unicon.adapters.topology.Unicon()

AttributeError: 'AttrDict' object has no attribute 'username'

```

**Comment by jeaubin** [comment]
Thanks to report it; we will fix the doc.

from pyats.topology import Testbed, Device, Interface, Link

testbed = Testbed('manuallyCreatedTestbed',
                  username='DefaultUsername',  
                  alias = 'iWishThisWasYaml',
                  passwords = {
                    'tacacs': 'lab',
                    'enable': 'lab',
                  },
                  servers = {
                    'tftp': {
                        'name': 'my-tftp-server',
                        'address': '10.1.1.1',
                    },
                  })

This will work as expected.

**Comment by simingy** [comment]
@jeaubin the example in the doc works for me... i think something else might be missing

```python
>>> from pyats.topology import Testbed, Device, Interface, Link
>>> # create your testbed
... testbed = Testbed('manuallyCreatedTestbed',
...                   alias = 'iWishThisWasYaml',
...                   passwords = {
...                     'tacacs': 'lab',
...                     'enable': 'lab',
...                   },
...                   servers = {
...                     'tftp': {
...                         'name': 'my-tftp-server',
...                         'address': '10.1.1.1',
...                     },
...                   })
>>> # create your devices
... device = Device('tediousProcess',
...                 alias = 'gimmyYaml',
...                 connections = {
...                     'a': {
...                         'protocol': 'telnet',
...                         'ip': '192.168.1.1',
...                         'port': 80
...                     }
...                 })
>>>
>>> # create your interfaces
... interface_a = Interface('Ethernet1/1',
...                         type = 'ethernet',
...                         ipv4 = '1.1.1.1')
>>> interface_b = Interface('Ethernet1/2',
...                         type = 'ethernet',
...                         ipv4 = '1.1.1.2')
>>>
>>> # create your links
... link = Link('loopback-1')
>>>
>>> # now let's hook up everything together
... # define the relationship.
... device.testbed = testbed
>>> device.add_interface(interface_a)
>>> device.add_interface(interface_b)
>>> interface_a.link = link
>>> interface_b.link = link
>>>
>>>
```

**Comment by urskog84** [comment]
@simingy, yes so far, tray to connect ti the device.

`device.connect()`

**Comment by urskog84** [comment]
Sill the same issue with code.

```
# import testbed objects
from pyats.topology import Testbed, Device, Interface, Link

# create your testbed
testbed = Testbed('myTestbed',
                  alias = 'testbed',
                  username='DefaultUsername',
                  passwords = {
                    'tacacs': 'truhe8a8',
                    'enable': 'lab',
                  },
                  )

# create your devices
device = Device('fspipswi001',
                alias = 'sw',
                connections = {
                    'a': {
                        'protocol': 'ssh',
                        'ip': '192.168.1.188',
                        'port': 22
                    }
                })

# now let's hook up everything together
# define the relationship.
device.testbed = testbed

sw = testbed.devices.fspipswi001
sw.connect()
```

**Comment by difuhu** [comment]
Hi @urskog84 
For this manual-creation, please modify your script as below:

# import testbed objects
from pyats.topology import Testbed, Device, Interface, Link

# create your testbed
testbed = Testbed('myTestbed',
                  alias='testbed',
                  )

# create your devices
device = Device('fspipswi001',
                alias='sw',
                tacacs={
                    'username': 'DefaultUsername',
                    'login_prompt': 'login:',
                    'password_prompt': 'Password:',
                },
                passwords={
                    'tacacs': 'truhe8a8',
                    'enable': 'lab',
                    'line': 'lab',
                },
                connections={
                    'a': {
                        'protocol': 'ssh',
                        'ip': '192.168.1.188',
                        'port': 22,
                    }
                })

# now let's hook up everything together
# define the relationship.
device.testbed = testbed

sw = testbed.devices.fspipswi001
sw.connect()


And we are introducing credential feature and will update this documentation as well.
Thank you for pointing out this issue.

**Comment by urskog84** [comment]
Can i not use stick the tacacs and the user part to the Testbed object. and not to device object? or is the the purees of the credential object?

**Comment by difuhu** [comment]
Hi @urskog84 
In manual-creation, Device object can't get values from Testbed object.
Currently, if you want to put username/password in testbed, please use pyats.topology.loader instead.

```
from pyats.topology import loader

testbed = """
testbed:
  name: myTestbed
  tacacs:
      username: 'DefaultUsername'
  passwords:
      tacacs: 'truhe8a8'
      enable: 'lab'
devices:
  fspipswi001:
    alias: sw
    os: iosxr
    type: iosxr
    connections:
      defaults:
        class: unicon.Unicon
      a:
        protocol: ssh
        ip: 192.168.1.188
        port: 22
"""

tb = loader.load(testbed)
sw = tb.devices['fspipswi001']
sw.connect()
```
The testbed content is better to be put in yaml file. For more detail, please refer to https://pubhub.devnetcloud.com/media/pyats/docs/topology/schema.html

**Comment by urskog84** [comment]
Big thanks for your help. keep up the god work!

Best regards
Petter
