### ISSUE TITLE
Run Time format

### ISSUE THREAD

**Issue by urskog84** [CiscoTestAutomation/pyats#29]
What have happen to the "Run Time format" in the HTML report?

i use `easypy test_job.py -html_logs html_folder` to generate the report.

Now the format is in `seconds.milliseconds`
Before `h:mm:ss`

![runtime_fromat](https://user-images.githubusercontent.com/18033678/67636159-eece6a80-f8cd-11e9-9abe-188dd33b4fde.PNG)

**Comment by simingy** [comment]
Thank you for reporting this issue. 

Team is looking into it. Will update on Monday.

**Comment by LilyHolms** [comment]
We have released a beta package which includes the patch updating runtime format. Please try:
```pip install --upgrade pyats.easypy```

Thanks.

**Comment by urskog84** [comment]
Thanks it work now!

keep up the good work
