### ISSUE TITLE
TypeError: argument of type 'module' is not iterable

### ISSUE THREAD

**Issue by Kernof** [CiscoTestAutomation/pyats#37]
I'm seeing the below error recently on executing the scripts  which had run without hitting any issues before in Ubuntu 14.04.5 LTS. 
Traceback (most recent call last):
  File "/home/natarar/pyats/bin/easypy", line 7, in <module>
    from ats.easypy import main
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1193, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1111, in create
  File "src/pyats/utils/import_utils/legacy.py", line 35, in pyats.utils.import_utils.legacy.LegacyLoader.create_module
  File "/home/natarar/pyats/lib/python3.4/site-packages/pyats/easypy/__init__.py", line 7, in <module>
    from .main import _default_runtime as runtime, main
  File "src/pyats/easypy/main.py", line 8, in init pyats.easypy.main
  File "/home/natarar/pyats/lib/python3.4/site-packages/pyats/log/__init__.py", line 1, in <module>
    from .cisco import (ScreenFormatter, ColouredScreenFormatter, ScreenHandler,
  File "src/pyats/log/cisco.py", line 17, in init pyats.log.cisco
  File "src/pyats/utils/utils.py", line 166, in init pyats.utils.utils
  File "src/pyats/utils/import_utils/misc.py", line 16, in pyats.utils.import_utils.misc.on_import
  File "src/pyats/utils/utils.py", line 168, in pyats.utils.utils._on_import_set_get_time
TypeError: argument of type 'module' is not iterable

**Comment by simingy** [comment]
which version of pyATS are you using? Please provide a pip list output.

**Comment by Kernof** [comment]
Package            Version
------------------ ---------
adium-theme-ubuntu 0.3.4
asn1crypto         0.22.0
bcrypt             3.1.3
certifi            2019.9.11
cffi               1.10.0
chardet            3.0.4
cryptography       2.0.3
Django             1.11.22
easypy             0.0.4
easysnmp           0.2.5
enum34             1.1.6
gevent             1.2.2
greenlet           0.4.12
html5lib           0.999
idna               2.6
invoke             0.10.1
ipaddress          1.0.18
numpy              1.13.3
pandas             0.21.1
paramiko           2.2.1
pbr                5.4.3
pip                20.0.1
pkginfo            1.5.0.1
ply                3.8
protobuf           2.6.1
py                 1.4.20
pyasn1             0.3.2
pycparser          2.18
pycryptodomex      3.4.7
PyNaCl             1.1.2
pysftp             0.2.9
pysmi              0.2.2
pysnmp             4.4.2
python-dateutil    2.6.1
pytz               2017.3
requests           2.18.4
selenium           3.141.0
setuptools         3.3
six                1.10.0
ssh-decorate       0.1
stevedore          1.31.0
telnetsrv          0.4
twine              1.5.0
unity-lens-photos  1.0
urllib3            1.22
virtualenv         12.0.1
virtualenv-clone   0.5.3
virtualenvwrapper  4.3.1
wheel              0.24.0
xmltodict          0.11.0
------------------------
:~$ pip3 list
apparmor (2.10.95)
apparmor.click (0.2ubuntu1)
apturl (0.5.2ubuntu4)
ATS (1.0.0)
Brlapi (0.6.1)
chardet (2.2.1)
checkbox-ng (0.3)
checkbox-support (0.2)
click (0.4.21.1ubuntu0.2)
colorama (0.2.5)
command-not-found (0.3)
defer (1.0.6)
feedparser (5.1.3)
friends (0.1)
html5lib (0.999)
httplib2 (0.8)
language-selector (0.1)
LibAppArmor (2.10.95)
louis (2.5.3)
lxml (3.3.3)
Mako (0.9.1)
MarkupSafe (0.18)
oauthlib (0.6.1)
onboard (1.0.1)
pip (1.5.4)
piston-mini-client (0.7.5)
plainbox (0.5.3)
ply (3.8)
pycrypto (2.6.1)
pycurl (7.19.3)
pygobject (3.12.0)
pyparsing (2.0.1)
python-apt (0.9.3.5ubuntu2)
python-dateutil (2.0)
python-debian (0.1.21-nmu2ubuntu2)
pyxdg (0.25)
requests (2.2.1)
setuptools (3.3)
six (1.5.2)
ubuntu-drivers-common (0.0.0)
ufw (0.34-rc-0ubuntu2)
unattended-upgrades (0.1)
unity-scope-audacious (0.1)
unity-scope-calculator (0.1)
unity-scope-chromiumbookmarks (0.1)
unity-scope-clementine (0.1)
unity-scope-colourlovers (0.1)
unity-scope-devhelp (0.1)
unity-scope-firefoxbookmarks (0.1)
unity-scope-gdrive (0.7)
unity-scope-gmusicbrowser (0.1)
unity-scope-gourmet (0.1)
unity-scope-guayadeque (0.1)
unity-scope-manpages (0.1)
unity-scope-musique (0.1)
unity-scope-openclipart (0.1)
unity-scope-texdoc (0.1)
unity-scope-tomboy (0.1)
unity-scope-virtualbox (0.1)
unity-scope-yelp (0.1)
unity-scope-zotero (0.1)
urllib3 (1.7.1)
usb-creator (0.2.23)
virtualenv (16.7.9)
wheel (0.24.0)
xkit (0.0.0)

**Comment by mdear** [comment]
I don't see the 'pyats' package in your pip install list.  Have you executed the "pip install pyats" command?

**Comment by simingy** [comment]
@Kernof  did you resort the issue?

**Comment by Kernof** [comment]
Hi, 

Issue is not resolved yet.

I did not use 'pip install pyats' rather I used the below,
sudo pip install virtualenv 
virtualenv pyats

since the below error was hitting on using the command 'pip install pyats',
natarar@jenkinsteaminode:~$ sudo pip3 install pyats
[sudo] password for natarar:
Downloading/unpacking pyats
  Could not find any downloads that satisfy the requirement pyats
Cleaning up...
No distributions at all found for pyats
Storing debug log for failure in /home/natarar/.pip/pip.log

I've attached the pip.log here:
[pip_log.txt](https://github.com/CiscoTestAutomation/pyats/files/4219142/pip_log.txt)

SERVER:
  Operating System: Ubuntu 14.04.5 LTS
            Kernel: Linux 4.2.0-27-generic
      Architecture: x86_64

**Comment by simingy** [comment]
@Kernof  update your pip/setuptools version:

```
pip install --upgrade pip setuptools
```

it shows you have v1.5.4 - it's too old to recognize some of the new wheel file formats, which we use.
