### ISSUE TITLE
How to pass parameter to parse() ?

### ISSUE THREAD

**Issue by sshuguan** [CiscoTestAutomation/pyats#45]
I wrote a parser script and saved it in my pyats tree as:
```
~/pyats/lib/python3.6/site-packages/genie/libs/parser/sros/show_card_detail.py
```

My code to call the parser:
```
from genie.libs.parser.sros.show_card_detail import ShowCardDetail
... # device connection codes
card_info = ShowCardDetail(device=dev).parse()
```

My question:
Is it possible to pass parameter such as "card_slot = 3" into parse(...) ?

Best regard,
sshuguan

**Comment by jeaubin** [comment]
Yes, 

card_info = ShowCardDetail(device=dev).parse(card_slot=3)

will do it
