### ISSUE TITLE
Not able to connect to device through proxy

### ISSUE THREAD

**Issue by vitodino** [CiscoTestAutomation/pyats#47]
I tried to connect to a router via a jumphost by following the guideline here:
https://pubhub.devnetcloud.com/media/unicon/docs/user_guide/proxy.html

**Here's my script:**
from genie.testbed import load
from pyats.topology import loader

tb = load('testbed2.yaml')
pe1 = tb.devices['router1']
pe1.connect()
pe1.execute('show version')

**Here's the testbed file:**
testbed:
  name: JUMPHOST_TESTBED
devices:
  linux1:
    os: linux
    type: linux
    credentials:
      default:
        username: aaaa
        password: bbbb
    connections:
      console:
        protocol: ssh
        ip: y.y.y.y
        port: 2222

  router1:
    os: iosxr
    type: router
    credentials:
      default:
        username: aaaa
        password: bbbb
    connections:
      default:
        protocol: telnet 
        ip: x.x.x.x
        port: 23
        sshtunnel: 
          host: linux1

I can connect to the router, but not able to execute any command after.

**Comment by danielgraziano** [comment]
Hi, it looks like you are combining two different methods - CLI Proxy and SSH Tunnel. The SSH Tunnel uses a server that is defined rather than a device. I suggest you do the following to use a device proxy instead:
![image](https://user-images.githubusercontent.com/1134387/80006688-3ad02580-8493-11ea-98f2-2cbb1a6e885a.png)

**Comment by vitodino** [comment]
@danielgraziano thanks for replying. 
I've tried your suggestion (changing ssh tunnel to proxy) and still got the same issue. Could it be related to my python version? I've tried 3.7 and now I'm using 3.6.9.

**Comment by danielgraziano** [comment]
@vitodino just to double check - is the routers hostname actually 'router1'? Or is that just an example? The reason I'm asking is the hostname and the name in your datafile must match otherwise it will hang after connecting

**Comment by vitodino** [comment]
Hi @danielgraziano , sorry for my late response. I hadn't got the time to test the script again. it's working now by using the exact hostname on the testbed. Thanks a lot for your help!
