### ISSUE TITLE
Cannot learn config for ios device

### ISSUE THREAD

**Issue by talha700** [CiscoTestAutomation/pyats#50]
'# pyats learn config  --testbed-file my.yaml'
 Learning '['config']' on devices '['S1']'
  0%|                                                                                                                      | 0/1 [00:00<?, ?it/s]

**Could not find the API under ios, and common**'

**Comment by simingy** [comment]
can you try with changing the os from ios to iosxe?

**Comment by tahigash** [comment]
@talha700 I think the workaround by @simingy would work for the issue.

I fixed this internally for `ios` and new release (20.5) will have the fix at end of this month. 
if you need the fix as soon as possible, let us know. We will release beta package for you after finishing internal review of the fix.

**Comment by talha700** [comment]
For now, it's working for my ios devices when switching type to iosxe ..... but I have to change this in my testbed ....curios that it will work as expected when taking snapshots & comparing other features like BGP,IS-IS, OSPF etc,. for ios devices when the type is selected to iosxe, as i want to do this with my same testbed file.... Thanks :)

**Comment by tahigash** [comment]
@talha700 we've just fixed and released minor version 20.4.1 with this fix. please upgrade by below command. `pyats learn config` should work with `os: ios`.

```
pip install genie.libs.sdk --upgrade

**Comment by talha700** [comment]
Thankyou ! , its working perfectly fine now
