### ISSUE TITLE
Help to view and print html logs 

### ISSUE THREAD

**Issue by ardenisov** [CiscoTestAutomation/pyats#51]
Hello! 
I have an issue with viewing log results in browser.
Result column overlaps Section column and I can not see details of test result
Also it prevent me for print out readable pdf report from this page.
Can you add possibility to move or hide columns in html result page?
<img width="951" alt="pyats log viewer" src="https://user-images.githubusercontent.com/11945032/83614637-256c1200-a58e-11ea-9f69-c6c3b2d8c8f6.PNG">

**Comment by karmoham** [comment]
Hi Ardenisov,

Thanks for reaching out!

Our team has a PDF report generation feature on their todo list.

Meanwhile, you can go with one of the below solutions;

- Avoid giving test cases names that are entire sentences so they actually fit on a page reasonably
- Zoom out your browser before printing

Let us know if you have any other questions!

Thanks,
Karim
