### ISSUE TITLE
How to get progress information in easypy aetest 

### ISSUE THREAD

**Issue by Baitanik** [CiscoTestAutomation/pyats#52]
we are executing like 

easypy -archive_dir archive_folder invoke_all_tests.py .

in that invoke_all_tests.py file we are executing jobs one by one in a loop with the following.
from ats.easypy import run
listoftest=[test1.py, test2.py]

run(listoftest[0], **vars(args)) 
run(listoftest[1], **vars(args))  etc.

and in test1.py , test2.py we have the actual common setup and aetest cases.. 

Is it possible to have progress information here. like how much percentage of test were executed like 30% is executed, 70% is remaining something like that .. maybe at task level..

Could you please help?

**Comment by bastell** [comment]
Hi,
There is no generic way to track the progress of tests in pyATS. Things like the UIDs filter and loops make it impossible to determine beforehand how many Testcases will actually be executed before the task is complete. However, you could make use of processors to make your own progress tracker for your specific tests. If you know how many tests will be executed, something like the following would print out the percentage completion of Testcases after each Testcase finishes. It uses a global post-processor passed from the jobfile to log the percentage completion.

```python
import logging
from pyats.aetest import Testcase
from pyats.easypy import run

class ProgressTracker:
    def __init__(self, expected_num):
        self.expected_num = expected_num
        self.count = 0
        self.logger = logging.getLogger('test_progress')

    def track(self, section):
        # global processors run on both testcases and test sections
        if isinstance(section, Testcase):
            self.count += 1
            self.logger.info('FINISHED {}/{}'.format(self.count,
                                                     self.expected_num))

def main(runtime):
    # Run with track method as global post-processor
    run(testscript = script_path,
        runtime = runtime,
        processors = {'post': [ProgressTracker(8).track]})
```

Is this close to what you are looking for? If you don't know the number of Testcases beforehand, there are other options as well, but this is a simple solution.
