### ISSUE TITLE
bgp.learn() exclude learing BGP routing table

### ISSUE THREAD

**Issue by walidamer711** [CiscoTestAutomation/pyats#53]
Due to full routing exists on the device, I need to exclude retrieving the BGP routing table while executing bgp.learn() function.

Every time bgp.learn() executes, the process stops because of the bgp table size. I presume that retrieved information would stored on the memory of the machine running the code. 

```python
genie_testbed = Genie.init(testbed)
pe1 = genie_testbed.devices['pe1']
pe1.connect()
abstract = Lookup.from_device(pe1)
bgp = abstract.ops.bgp.bgp.Bgp(pe1)
bgp.learn()
```

**Comment by xiaoxinz-cisco** [comment]
Hi @walidamer711 ,

Would you mind take a look at this documentation:
https://developer.cisco.com/docs/genie-docs/
which shows various usage of `learn()`

Thanks,
