### ISSUE TITLE
Can't install pyats, using python 3.6.6

### ISSUE THREAD

**Issue by dercar** [CiscoTestAutomation/pyats#54]
I currently have an issue where I can't install pyats on python 3.6.6

ERROR: Could not find a version that satisfies the requirement pyats (from versions: none)
ERROR: No matching distribution found for pyats

My python version and pip version
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
pip version 20.2.2

**Comment by tahigash** [comment]
Hi @dercar, I assume you are trying to use pyATS on Windows. but we don't support to run pyATS on Windows natively. please use WSL(Windows Subsystem for Linux) and install pyATS on WSL. (or use pyATS on Linux)

**Comment by dercar** [comment]
tahigash, you're right. I am trying to install and run it on a Windows platform.
I'll try it on a WSL. Thanks.
