### ISSUE TITLE
Problem with device's filter

### ISSUE THREAD

**Issue by nazarko-es** [CiscoTestAutomation/pyats#57]
Hello, i run genie learn or pyats learn and use --device filter so that learning runs for several devices. When i do it an error occurs. If i run lerning for one device it works. For example, i run:

genie learn all --testbed-file ../pod/testbed.yml --output ../pod/network_state/running/ --devices "device1,device2"

And i see an error:

local variable 'dev' referenced before assignment

But command below works:

genie learn all --testbed-file ../pod/testbed.yml --output ../pod/network_state/running/ --devices "device1"

**Comment by xiaoxinz-cisco** [comment]
Hi @nazarko-es ,

As the [documentation](http://wwwin-pyats.cisco.com/cisco-shared/genie/latest/cli/genie_learn.html#genie-learn) describes, please use a list of devices instead.

Thanks

**Comment by nazarko-es** [comment]
I can't open this link, fix it please

**Comment by xiaoxinz-cisco** [comment]
Hi @nazarko-es ,

Please try this one: https://developer.cisco.com/docs/genie-docs/

<img width="718" alt="nazarko" src="https://user-images.githubusercontent.com/60668974/92130644-f9ea0500-edd2-11ea-8a89-c5b450bbe5b3.PNG">

**Comment by nazarko-es** [comment]
Thank you, this link is work, but i don't see in documentation about list format. How must i give list-type to genie learn? I tried to use follow formats:
--devices device1,device2
--devices "device1,device2"
--devices [device1,device2]
--devices "device1","device2"
All of them don't work

**Comment by xiaoxinz-cisco** [comment]
Hi @nazarko-es ,

Sorry about that, it is a typo in our documentation. I will fix it today. 

Please try `--devices device1 device2`

**Comment by nazarko-es** [comment]
Thanks, it is work. Also genie learn --help have says the same thing(List of devices, comma separated)
