### ISSUE TITLE
pyats.topology loader not working like genie.testbed load

### ISSUE THREAD

**Issue by rick-allen-206** [CiscoTestAutomation/pyats#59]
When using `from pyats.topology import loader` as the plugin to load my testbed.yml trying to .parse('show version) raises attribute error "device object has no attribute 'parse'" 

However, if I use the `from genie.testbed import load` the .parse mentioned above works just fine.

Here is a sample of the Code I'm trying to use

```
from pyats.topology import loader
testbed = loader.load('testbed.yml')
testbed.devices['device1'].connect()
output = testbed.devices['device1'].parse('show version')
print(output)
```

**Comment by jeaubin** [comment]
That's correct,  to use .parse and other apis, you need to use the Genie loader.

```
from genie.testbed import load
testbed = load('testbed.yml')
testbed.devices['device1'].connect()
output = testbed.devices['device1'].parse('show version')
print(output)

```

I'll be closing this, as this is not an issue.
