### ISSUE TITLE
Can't Install pyATS on 3.9

### ISSUE THREAD

**Issue by evboggs302** [CiscoTestAutomation/pyats#60]
When trying to install pyATS using python3.9, I get the below error:
`ERROR: Could not find a version that satisfies the requirement pyats (from versions: none)
ERROR: No matching distribution found for pyats`

I'm using a Mac running the latest version.

**Comment by jeaubin** [comment]
Thats correct, pyats is not supported 3.9 yet,  we are supported
3.5 3.6 3.7 3.8  and soon 3.9
