### ISSUE TITLE
testbed created  with jumphost

### ISSUE THREAD

**Issue by markheinemann** [CiscoTestAutomation/pyats#61]
Hi

I wish to create a testbed.yaml file containing a jumphost config , as all ssh connections have to go through this device first.

I am creating this testbed.yaml by  writing a.  xls file, and adding additional column headed 'proxy' 
im leaving the cell blank for the jumphost itself and populating for each device with 'jumphost'

my xls columns read:
hostname,ip,proxy,username,password,enable_password,protocol,os,type 

Once created the testbed , I have discovered that the key value pair for proxy: jumphost  is created in the wrong part of the created yaml file

It appears at the same indent and  inbetween 'os' and 'type'   in each device - and this throws an error when i validate the yaml file

IF i move proxy:jumphost, to same indent and inbetween the 'ip' and 'protocol' , the yaml file is then working successfully
and i can 'learn' from it

i guess my excel is somehow formatted incorrectly ?

thanks :)

**example BAD**

       devices:
        jumphost:
    connections:
      cli:
        ip: 10.10.10.10
        protocol: ssh
    credentials:
      default:
        password: '%ASK{}'
        username: myname
      enable:
        password: '%ASK{}'
    os: linux
    type: linux
      device1:
    connections:
      cli:
        ip: 20.20.20.20
        protocol: ssh
    credentials:
      default:
        password: '%ASK{}'
        username: myname
      enable:
        password: '%ASK{}'
    os: nxos
    proxy: jumphost        <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    type: nexus

**example GOOD ( by moving proxy:jumphost )**

       devices:
        jumphost:
    connections:
      cli:
        ip: 10.10.10.10
        protocol: ssh
    credentials:
      default:
        password: '%ASK{}'
        username: myname
      enable:
        password: '%ASK{}'
    os: linux
    type: linux
      device1:
    connections:
      cli:
        ip: 20.20.20.20
        proxy: jumphost          <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<moved
        protocol: ssh
    credentials:
      default:
        password: '%ASK{}'
        username: myname
      enable:
        password: '%ASK{}'
    os: nxos
    type: nexus

**Comment by ThomasJRyan** [comment]
Hi there! I've fixed this issue up with this PR: https://github.com/CiscoTestAutomation/pyats.contrib/pull/18

You should be good to go now
