### ISSUE TITLE
PYats connection to router via console/ terminal Server

### ISSUE THREAD

**Issue by pyatsMonster** [CiscoTestAutomation/pyats#63]
Hello, this is my first time opening an issue.
i'm having a really hard time figuring out how to use pyats testbed file to connect to devices via console server.

****
linux server executing pyats job ==> ssh to (console server) <port-number-used_by_device>==> username/ password prompt of (cisco ncs5K router serial cli)
****
i used to connect via console server using netmiko library, but i'm working with pyats since it makes my life way easier

 i tried the proxy device configuraiton on the testbed file but it blocks when the prompt shows the second username and password to connect to the router cli.
si there any enhancement or new version that supports this feature? or does already exists.
Thanks in advance
Nassim

**Comment by LenzDong** [comment]
Hi, 
Could you share the log and testbed file information?
You can send it to pyats-support-ext@cisco.com
Thanks,

**Comment by simingy** [comment]
@pyatsMonster welcome to pyATS... oh wait, it's a monster...

**Comment by pyatsMonster** [comment]
@LenzDong i sent the logs via the email provided.
Thanks in advance for your help.
regards,

**Comment by sohalevi** [comment]
Hi, I came across your case while searching for the exact same thing.
Did you receive a solution? Can you share it with me?

Thank you!

**Comment by pyatsMonster** [comment]
Hello,
Sadly I did not bother too much with it , Cisco itself is not maintaining
and evolving pyats,
I turned to netmiko where in the connection settings you can specify
console server
I’m not longer in that company to show you exactly how I did .
But check the netmiko library it’s as efficient as pyats, and if you want
your output in json , use textsfm templates included with netmiko
Best regards
