### ISSUE TITLE
Need help in attaching custom file in the pyATS mail reports

### ISSUE THREAD

**Issue by krishnamurth** [CiscoTestAutomation/pyats#64]
I would like to attach a custom log file in the mail report that is sent out. Reading through the DOC : https://pubhub.devnetcloud.com/media/pyats/docs/easypy/email.html#easypy-email-notification

Suggests that inside the jobfile - the runtim object needs to be used for creating a attachment. The following is the code-snippet that i am trying out - but i am not getting the mail report with the custom attachment. Could someone let me know on how to fix this ?

```
        from pyats.easypy.email import TextEmailReport

        attachment_path = f'/home/mypath/test.txt'
        logger.info(f'Path:: {attachment_path }')

        report_obj = TextEmailReport(runtime, attachment=attachment_path )
        setattr(runtime, 'mail_report', report_obj)
```

**pyATS Version**
```
pyats version
You are currently running pyATS version: 19.4.0
Python: 3.6.9 [64bit]

  Package              Version
  -------------------- -------
  pyats                19.4.0 
  pyats.aereport       19.4.0 
  pyats.aetest         19.4.0 
  pyats.async          19.4.0 
  pyats.connections    19.4.0 
  pyats.datastructures 19.4.0 
  pyats.easypy         19.4.2 
  pyats.examples       19.4.0 
  pyats.kleenex        19.4.1 
  pyats.log            19.4.0 
  pyats.results        19.4.0 
  pyats.tcl            19.4.0 
  pyats.templates      19.4.0 
  pyats.topology       19.4.0 
  pyats.utils          19.4.3 
```

**Comment by krishnamurth** [comment]
Thanks a lot for the update, I will try this out and will update if it works.

**Comment by krishnamurth** [comment]
@thaixuann : I see a weird behavior after setting the attributes (Pyats Version  20.10) ,

```
attachment_path = '/path/to/attachment.txt'
runtime.job.report.attachment = attachment_path 
```

with the above code, if i run my job file - the mail send is getting failed with the below error
```
2020-12-17T07:13:04: %EASYPY-INFO: Sending report email...
2020-12-17T07:13:04: %EASYPY-INFO: Missing SMTP server configuration, or failed to reach/authenticate/send mail. Result notification email failed to send.
2020-12-17T07:13:05: %EASYPY-INFO: Done!
```

But if comment out the attachment part (the code above) - I see the mail is getting sent properly.
```
2020-12-17T07:13:54: %EASYPY-INFO: Sending report email...
2020-12-17T07:13:57: %EASYPY-INFO: Done!
```

Could you please let me know if this is correct way of doing.

**Comment by thaixuann** [comment]
Hello @krishnamurth ,
Could you please check the SMTP server configuration?
https://pubhub.devnetcloud.com/media/pyats/docs/easypy/email.html#custom-smtp-information

Thanks,
--Thai.

**Comment by krishnamurth** [comment]
@thaixuann : The SMTP configurations are correct and it works fine if I don't set the attachment. 

The issue is when the attachment attribute is set, the mail send fails

**Comment by thaixuann** [comment]
Hello @krishnamurth ,
Could you please check to see if you configured these parameters?
https://pubhub.devnetcloud.com/media/pyats/docs/configuration/index.html
```

# smtp host url/ip and port
smtp.host = <value>
smtp.port = <port>

# smtp to use TLS/ssl
smtp.ssl = <True/False>

# smtp connection timeout (default to 30s)
smtp.timeout = <timeout in seconds>

# smtp username/password for authentication
smtp.username = <username>
smtp.password = <password>
```

Thanks,
--Thai.

**Comment by krishnamurth** [comment]
Yea, these are already set in /etc/pyats.conf, and there is no change in this file. 

Again as I said earlier this works fine when we don't override the attachment attribute.

When we override the attachment attribute using **runtime.job.report.attachment = <some_path>**, the mail begins failing

**Comment by thaixuann** [comment]
Hello @krishnamurth ,
Sorry for the run around. Please use this:

`attachment_path = ["/path/to/attachment.txt"]`

That should fix your issue. We are working to improve this email. However, there are some tips:
1) you can use `-v` to see the debug messages
2) there are a size limit set by the server which is about 10MB
3) right now the attachment is only working with text file. We are adding for attach non-text file

Please try and let me know if there is any other issue.

Thanks,
--Thai.

**Comment by krishnamurth** [comment]
@thaixuann : thanks a lot for the help. Setting the attachment as list works 👍 . 

Please do update the readme docs, so that it would be easy for ppl trying to use it.
