### ISSUE TITLE
error running pyats

### ISSUE THREAD

**Issue by kevinyohe** [CiscoTestAutomation/pyats#65]
Trying to install pyats[full] on python 3.6.9 or 3.8.1 and when running the pyats command I get this error:
.....venv/lib/python3.8/site-packages/async_lru.py", line 182, in wrapper
    raise RuntimeError(
RuntimeError: Coroutine function is required, got <cyfunction LogSection.child_execute at 0x7faa484a5380>

**Comment by LenzDong** [comment]
Hi,

We just released new pyats.log v20.12.1 package to fix this issue.
Could you update your package and try again.

Command to upgrade:
pip install --upgrade pyats.log
https://pypi.org/project/pyats.log/20.12.1/
