### ISSUE TITLE
Not able to install pyats locally

### ISSUE THREAD

**Issue by shivsach** [CiscoTestAutomation/pyats#7]
(.venv-py36) SHIVSACH-M-F0US:bin shivsach$ pip install pyats
Collecting pyats
  Could not find a version that satisfies the requirement pyats (from versions: )
No matching distribution found for pyats

**Comment by siming85** [comment]
what's your system architecture?
is this linux, mac? 32-bit? 64-bit?

what's the python version?

and, what's your pip version? (please provide `pip list` output)

**Comment by shivsach** [comment]
Hi Siming,
 
I have 64 bit mac. I have tried to install pyats on both python 2.7 and python 3.7 but none of them worked. Upgraded pip, imported requests , created virtualenv in 2.7 as well as in 3.7. Here is pip list:
 
SHIVSACH-M-F0US:Users shivsach$ pip list
Package    Version  
---------- ---------
certifi    2018.8.24
chardet    3.0.4    
idna       2.7      
pip        18.0     
requests   2.19.1   
setuptools 39.0.1   
urllib3    1.23     
virtualenv 16.0.0   
SHIVSACH-M-F0US:Users shivsach$ 
 
I have tried various things but none of them worked. Although I have pyats on server but not able to install locally on my computer.

**Comment by siming85** [comment]
pyats doesn't yet support Python 3.7. Use Python 3.4, 3.5 or 3.6.

**Comment by shivsach** [comment]
Thank you, installed on Python3.6.6

**Comment by siming85** [comment]
anytime

**Comment by siming85** [comment]
anytime

**Comment by vpendyal73** [comment]
I cant install it on ubuntu.
sda@SDA-WiFi-Graphana:~/.vnc$ uname -a
Linux SDA-WiFi-Graphana 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
sda@SDA-WiFi-Graphana:~/.vnc$ pip install pyats
Collecting pyats
  Could not find a version that satisfies the requirement pyats (from versions: )
No matching distribution found for pyats
sda@SDA-WiFi-Graphana:~/.vnc$ sudo pip install pyats
[sudo] password for sda:
The directory '/home/sda/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/sda/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pyats
  Could not find a version that satisfies the requirement pyats (from versions: )
No matching distribution found for pyats
sda@SDA-WiFi-Graphana:~/.vnc$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
sda@SDA-WiFi-Graphana:~/.vnc$

**Comment by vpendyal73** [comment]
fixed it. that pip was referring to pip2 and once I installed and used pip3, it worked.

**Comment by Kishankmr** [comment]
Can i install it on windows?
i have below running 
Python 3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:27:37) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.


>pip list
pip (7.1.2)
setuptools (18.2)

but i see this error
>pip install pyats
Collecting pyats
  Could not find a version that satisfies the requirement pyats (from versions: )
No matching distribution found for pyats
