### ISSUE TITLE
Error with api feature copy_from_device pyats 20.12

### ISSUE THREAD

**Issue by naciohr** [CiscoTestAutomation/pyats#71]
Dear support,

I ran into the following problem in pyats 20.12 when using the api feature **copy_from_device**. The command works correctly in pyats version 20.10.

I have got a certificate hosted in a linux server to download into a WLC 9800 series. The result of the command shows the following that yields an error in the end:

```
scp userX@1.2.3.4:/home/userX/certificateX. ^p12 flash:
```

Running the command on 20.10 same conditions yields:

```
copy scp://1.2.3.4//home/userX/certificateX.p12 flash:
```

I confirm certificateX.p12 exists in the server and, like I commented, it works correctly for 20.10.

Should you need further details, don't hesitate to enquire.

Many thanks.

**Comment by ahersi2-cisco** [comment]
Hi naciohr,

Can you please provide a more detailed log of the error? If you even want to provide the portion of the log that generated the error that would also be great.

Thank you,
Abdurahman

**Comment by ahersi2-cisco** [comment]
closing the issue for now. Please reopen it if issue persists, and please provide a more complete log and I'll look into this.
