### ISSUE TITLE
missing acl information in parse for show ip interface (iosxe, ios) /show access list summary (nxos)

### ISSUE THREAD

**Issue by igor-saiko** [CiscoTestAutomation/pyats#73]
Dear Support
I have found that acl information is not full for  show ip interface (iosxe, ios) /show access list summary (nxos)

genie parse "show ip interface"
parsed missing inbound access-list
output files are attached for console and parsed 
(attached for one of interface, however same happens in "show ip interface")

genie parse "show access-lists summary"
parsed missing all configured access-lists
output files are attached for console and parsed 

host inforamtion is removed from files and file names

pyats version check
You are currently running pyATS version: 20.12
Python: 3.8.5 [64bit]

  Package                      Version
  ---------------------------- -------
  genie                        20.12.2
  genie.libs.clean             20.12.1
  genie.libs.conf              20.12
  genie.libs.filetransferutils 20.12
  genie.libs.health            20.12
  genie.libs.ops               20.12
  genie.libs.parser            20.12
  genie.libs.robot             20.12
  genie.libs.sdk               20.12
  genie.telemetry              20.12
  genie.trafficgen             20.12
  pyats                        20.12
  pyats.aereport               20.12
  pyats.aetest                 20.12
  pyats.async                  20.12
  pyats.connections            20.12
  pyats.contrib                20.12
  pyats.datastructures         20.12
  pyats.easypy                 20.12
  pyats.kleenex                20.12
  pyats.log                    20.12.2
  pyats.reporter               20.12.1
  pyats.results                20.12
  pyats.robot                  20.12
  pyats.tcl                    20.12
  pyats.topology               20.12
  pyats.utils                  20.12
  unicon                       20.12
  unicon.plugins               20.12
[show-access-list-summary_console.txt](https://github.com/CiscoTestAutomation/pyats/files/5829895/show-access-list-summary_console.txt)
[show-access-list-summary_parsed.txt](https://github.com/CiscoTestAutomation/pyats/files/5829898/show-access-list-summary_parsed.txt)
[show-ip-interface-vlan301_console.txt](https://github.com/CiscoTestAutomation/pyats/files/5829899/show-ip-interface-vlan301_console.txt)
[show-ip-interface-vlan301_parsed.txt](https://github.com/CiscoTestAutomation/pyats/files/5829900/show-ip-interface-vlan301_parsed.txt)

**Comment by tahigash** [comment]
thank you for reporting the issue. I've fixed the issues internally and the fixed parsers are now under review. The fixes will be ready in 20.1 release (end of Jan).

Please let me know if you need beta package in advance.

**Comment by tahigash** [comment]
We will release new version 20.1 which has above fix tomorrow.
So, closing this issue. Please feel free to reopen if same issue with new release.
