### ISSUE TITLE
Is it possible to customize the log format 

### ISSUE THREAD

**Issue by krishnamurth** [CiscoTestAutomation/pyats#76]
Hi - We have a requirement to customize the log message format - we would want to log the module/method name/line number in addition - whenever the logging is invoked. Tried to customize the log format, but seems like the custom format was only getting printed in the stdout, but the log message was still adhering to the standard format.

```
import logging
from pyats.log import TaskLogHandler

date_format = "%d-%b-%y %H:%M:%S"
log_format = "[%(asctime)-s] - [%(levelname)s] - [%(filename)s:%(funcName)s:%(lineno)d] - " \
             "[%(threadName)s] - '%(message)s'"

logging.basicConfig(format=log_format, datefmt=date_format)
logger = logging.getLogger(__name__)
handler = TaskLogHandler("/path/to/log")
logger.addHandler(handler)
logger.setLevel(logging.DEBUG)

```

Please let us know if formatting the TaskLog to custom user format (python logging format) is supported ?

**Comment by ThomasJRyan** [comment]
Hi there,

The way you're going about this is on the right track but you're just missing the mark by a bit.

To add in custom handlers that would have the format you're looking for, do something along these lines:
```python
from pyats.log import TaskLogHandler, ScreenHandler
logger = logging.getLogger(__name__)

# TaskLogHandler will handle logging to a file
TLHandler = TaskLogHandler("/path/to/log")
TLHandler.formatter._fmt = "this formats your message"
TLHandler.formatter.datefmt = "this formats your time"

# ScreenHandler will handler logging the screen
ScHander = ScreenHandler("/path/to/log")
ScHandler.formatter._fmt = "this formats your message"
ScHandler.formatter.datefmt = "this formats your time"

# Add your handlers to your logger
logger.addHandler(TLHandler)
logger.addHandler(ScHandler)
```
Doing the above will add your custom handlers **on top** of the existing root handlers. Causing you to have **both your custom and pyATS logging simultaneously**

If you wanted to replace the root handlers entirely however, you could find them like so
```python
root = logging.getLogger()
root.handlers
```
In there will be a `ScreenHandler`, a `TaskLogHandler`, and an `AEReportDetails` handler which you can modify using their `formatter._fmt` and `formatter.datefmt` variables.

I hope this is clear and can help you reach what you're trying to accomplish

**Comment by krishnamurth** [comment]
@ThomasJRyan : Thanks for the quick response. I will try the suggested change and update in this thread.

**Comment by krishnamurth** [comment]
@ThomasJRyan : With the above code, i still the log format unaltered, and the format is still the old format.

```
from pyats.log import TaskLogHandler, ScreenHandler
import logging

logger = logging.getLogger(__name__)

# TaskLogHandler will handle logging to a file
tlHandler = TaskLogHandler("log/file_path")
tlHandler.formatter._fmt = "%(message)s"
tlHandler.formatter.datefmt = "%d-%b-%y %H:%M:%S"


# Add your handlers to your logger
logger.addHandler(tlHandler)
logger.critical("Critical Message")
```

```
<hostname>$ cat checkers.log 
0: my_system: 06-Feb-21 03:56:58: %SCRIPT-2-CRITICAL: %[pid=5692][pname=MainProcess]: Critical Message
```

If you notice, the log message format just says to log the message (and not other fields), but in the obtained log i can see the custom cisco format.

**Comment by krishnamurth** [comment]
Any update on this issue ?

**Comment by jeaubin** [comment]
pyATS is using the typical python logger. All info is here: https://docs.python.org/3/library/logging.html and here: https://pubhub.devnetcloud.com/media/pyats/docs/log/index.html 

Closing as this is not an issue

**Comment by krishnamurth** [comment]
@jeaubin : I still don't understand the logic here. If pyATS logging adheres to standard python logging, then it should be straightforward to customize the message format, but it isn't. For some reason, the log file generated by PyATS never adheres to the custom format.

My sample code  below, please correct if anything is missed,

```
from pyats.log import TaskLogHandler, ScreenHandler, TaskLogFormatter

import logging

date_fmt = "%d-%b-%y %H:%M:%S"
msg_fmt = "%(message)s"

logger = logging.getLogger(__name__)

my_formatter = TaskLogFormatter()
my_formatter.MESSAGE_FORMAT = msg_fmt
my_formatter._fmt = msg_fmt

tl_handler = TaskLogHandler("/path/to/log/checkers.log")
tl_handler.setFormatter(my_formatter)
tl_handler.formatter._fmt = "%(messages)s"
tl_handler.formatter.datefmt = date_fmt

logger.addHandler(tl_handler)
logger.critical("Critical Message")
```

And the resulting log below,
```
<hostname>$ cat checkers.log 
0: my_system: 06-Feb-21 03:56:58: %SCRIPT-2-CRITICAL: %[pid=5692][pname=MainProcess]: Critical Message
```

If possible could you please post a snippet of code solving the above requirement, that i can use to customize my task log handler. 
I want to make pyats write the logs in the specific format (lets say log **message alone and not other details**), is this possible ? If yes, a sample code snippet would be helpful.

**Default Format That PyATS logs with**
```
38: dev-test: 2021-02-13T00:51:36: %CUSTOM-7-DEBUG: %[pid=66006][pname=Task-1]: This is Debug Message
```

**The Format that i want**
```
38: This is Debug Message
```

Is this possible ? If yes - please post a working code snippet
