### ISSUE TITLE
error with "show interface" parser in nxos

### ISSUE THREAD

**Issue by novolyus** [CiscoTestAutomation/pyats#78]
_****            error shown           *****_

pyats parse "show interface" --testbed-file testbed.yaml --devices N5K_DEVICE
  0%|                                                                                                                                                | 0/1 [00:00<?, ?it/s]Issue with the parser show interface

Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 339, in genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 555, in genie.conf.base.device.Device.parse
  File "src/genie/conf/base/device.py", line 582, in genie.conf.base.device.Device._get_parser_output
  File "src/genie/metaparser/_metaparser.py", line 272, in genie.metaparser._metaparser.MetaParser.parse
  File "/home/pyats2/lib64/python3.6/site-packages/genie/libs/parser/nxos/show_interface.py", line 719, in cli
    interface_dict[interface]['beacon'] = beacon
KeyError: ''

_****             platform:                *****_
Software
  BIOS:      version 2.1.7
  Power Sequencer Firmware: 
             Module 1: v4.0
             Module 1: v4.0
  Fabric Power Sequencer Firmware: Module 1: version v4.0
  Microcontroller Firmware:        version v0.0.0.15
  QSFP Microcontroller Firmware:   
             Module 1: v2.0.0.0
  SFP Microcontroller Firmware:   
             Module 1: v1.3.0.0
  CXP Microcontroller Firmware:   
             Module not detected
  kickstart: version 7.3(3)N1(1)
  system:    version 7.3(3)N1(1)
  BIOS compile time:       06/16/2016
  kickstart image file is: bootflash:///n6000-uk9-kickstart.7.3.3.N1.1.bin
  kickstart compile time:  4/27/2018 9:00:00 [04/27/2018 23:25:57]
  system image file is:    bootflash:///n6000-uk9.7.3.3.N1.1.bin
  system compile time:     4/27/2018 9:00:00 [04/27/2018 23:28:04]

Hardware
  cisco Nexus 5672UP Chassis ("Nexus 5672UP Supervisor")
  Intel(R) Xeon(R) CPU  @ 1.80 with 8243276 kB of memory.
  Processor Board ID FOC19235RYF

**Comment by KamyarZiabari** [comment]
Hello
Can you please send your device output of when you run show interface on your box to 
pyats-support-ext@cisco.com 

This way I could generate the error on my end and put the fix in place 

Thank you!
