### ISSUE TITLE
bash_console() stuck in pyats 21.3

### ISSUE THREAD

**Issue by jpmateo022** [CiscoTestAutomation/pyats#90]
Hi, It seems when using bash_console() gets stuck, it's not executing the next command but admin_bash_console works fine.

**Comment by jpmateo022** [comment]
Additional info. I revered to 21.1 version to make the bash_console working,.

**Comment by danielgraziano** [comment]
@jpmateo022 can you please share the logs where it did not work? If possible, you can send them to pyats-support-ext@cisco.com so they aren't shared in an open forum.

**Comment by jpmateo022** [comment]
@danielgraziano Sure I'll send the logs

**Comment by danielgraziano** [comment]
Hi @jpmateo022 I've found the issue and the fix is currently getting reviewed. It will be released in version 21.4 unless you would like me to release a beta pkg early. Please let me know.

**Comment by danielgraziano** [comment]
Closing this issue, if you want a beta package before the 21.4 release please create a new issue and link this one asking for it.
