### ISSUE TITLE
Getting error - "parse_genie: Genie package is not installed. To install, run 'pip install genie'."

### ISSUE THREAD

**Issue by vikram112in2000** [CiscoTestAutomation/pyats#91]
Hi,

I am getting an error when i run playbook for parsing using genie (pyats)  - "parse_genie: Genie package is not installed. To install, run 'pip install genie'."

1. However i have already installed pyats and genie.
2. I use WSL linux in windows VDI and use debian linux 10 (since some supporting packages for ubuntu wouln't get installed and suspect company proxy to be blocking).
3. Pyhton 2 was inatlled by default with ansible. I then installed python 3 installed and made the playubook to refer to python 3 using below command.
vars:
    ansible_python_interpreter: /usr/bin/python3
4. I then changed pip from pip2 to pip3 using below command
alias pip=pip3
5. When i run 'pip install genie', it says already installed yet i keep getting this error each time.
6. Other imp command i have already run are:
ansible-galaxy collection install --ignore-certs clay584.parse_genie 
 pip3 install pyats[full] 
7. Pyats documentation says that it has been tested with CentOS, RHEL, Ubuntu, Alpine but it does NOT explicitely say that it won't work with other linux version. Is me using debian linuix the problem?

Whst should i do to fix it?

root@:~# pip --version
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)

root@:~# ansible --version
ansible 2.9.20
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]

root@:~# python --version
Python 2.7.16

root@:~# python3 --version
Python 3.7.3

Thanks,
Vikram

**Comment by tahigash** [comment]
I'm assuming this is related to your environment for Ansible which we cannot support.

Did you see error with the command `pip3 install pyats[full]`?
if you see `pyats` packages by `pip3 list` command, installation was successfully done and need to investigate the env with Ansible. You may need to reach out to Ansible community for support in that case.
