### ISSUE TITLE
Cannot create testbed from excel

### ISSUE THREAD

**Issue by ragu2k8** [CiscoTestAutomation/pyats#96]
i am clueless about below error ,everything seems fine  as per documentation and i tried installing 'pip install pyats.contrib'. no luck any help would be appreciated?

(pyats_dev) rr@Ragu yaml % pyats create testbed Sample.xlsx --output testsample.yaml -v
Traceback (most recent call last):
  File "src/pyats/cli/base.py", line 207, in pyats.cli.base.Command.main
  File "src/pyats/cli/base.py", line 337, in pyats.cli.base.CommandWithSubcommands.run
  File "src/genie/cli/commands/create_testbed.py", line 43, in genie.cli.commands.create_testbed.CreateTestbed.run
Exception: please make sure pyats.contrib is installed. If not, please do 'pip install pyats.contrib'.

invalid option: Sample.xlsx

please make sure pyats.contrib is installed. If not, please do 'pip install pyats.contrib'.

invalid option: Sample.xlsx

########################################################
yaml % pyats version check                                         
You are currently running pyATS version: 21.1
Python: 3.8.6 [64bit]

  Package                      Version
  ---------------------------- -------
  genie                        21.1.2 
  genie.libs.clean             21.1   
  genie.libs.conf              21.1   
  genie.libs.filetransferutils 21.1   
  genie.libs.health            21.1   
  genie.libs.ops               21.1   
  genie.libs.parser            21.1   
  genie.libs.sdk               21.1.2 
  pyats                        21.1   
  pyats.aereport               21.1   
  pyats.aetest                 21.1   
  pyats.async                  21.1   
  pyats.connections            21.1   
  pyats.datastructures         21.1   
  pyats.easypy                 21.1   
  pyats.kleenex                21.1   
  pyats.log                    21.1   
  pyats.reporter               21.1   
  pyats.results                21.1   
  pyats.tcl                    21.1   
  pyats.topology               21.1   
  pyats.utils                  21.1.2 
  unicon                       21.1   
  unicon.plugins               21.1

**Comment by danielgraziano** [comment]
@ragu2k8 `pyats.contrib` still is not installed. Can you share what's not working with the install? Including @LukasMcClelland for further help

**Comment by ragu2k8** [comment]
@danielgraziano thanks for reply . i installed `pyats.contrib` couple of times but still getting same error 
so below commands does not work,
pyats create testbed Sample.xls --output my_testbed.yaml
pyats create testbed --output test_inter.yaml --encode-password

i tried with 20.4


(pyats_dev) ragu@ragu-M-V132 yaml % pip install pyats.contrib
Collecting pyats.contrib
  Using cached pyats.contrib-21.4-py3-none-any.whl (51 kB)
Requirement already satisfied: xlwt in /Users/ragu/Desktop/ISE/prod/fullstack/iseapp/iseappstack/pyats_dev/lib/python3.8/site-packages (from pyats.contrib) (1.3.0)
Requirement already satisfied: requests in /Users/ragu/Desktop/ISE/prod/fullstack/iseapp/iseappstack/pyats_dev/lib/python3.8/site-packages (from pyats.contrib) (2.25.1)
Requirement already satisfied: xlsxwriter in /Users/ragu/Desktop/ISE/prod/fullstack/iseapp/iseappstack/pyats_dev/lib/python3.8/site-packages (from pyats.contrib) (1.4.0)
Requirement already satisfied: xlrd==1.2 in /Users/ragu/Desktop/ISE/prod/fullstack/iseapp/iseappstack/pyats_dev/lib/python3.8/site-packages (from pyats.contrib) (1.2.0)
Requirement already satisfied: ansible in /Users/ragu/Desktop/ISE/prod/fullstack/iseapp/iseappstack/pyats_dev/lib/python3.8/site-packages (from pyats.contrib) (3.3.0)
Requirement already satisfied: ansible-base<2.11,>=2.10.8 in /Users/ragu/Desktop/ISE/prod/fullstack/iseapp/iseappstack/pyats_dev/lib/python3.8/site-packages (from ansible->pyats.contrib) (2.10.8)
Requirement already satisfied: jinja2 in /Users/ragu/Desktop/ISE/prod/fullstack/iseapp/iseappstack/pyats_dev/lib/python3.8/site-packages (from ansible-base<2.11,>=2.10.8->ansible->pyats.contrib) (2.11.3)
Requirement already satisfied: PyYAML in /Users/ragu/Desktop/ISE/prod/fullstack/iseapp/iseappstack/pyats_dev/lib/python3.8/site-packages (from ansible-base<2.11,>=2.10.8->ansible->pyats.contrib) (5.4.1)
Requirement already satisfied: cryptography in /Users/ragu/Desktop/ISE/prod/fullstack/iseapp/iseappstack/pyats_dev/lib/python3.8/site-packages (from ansible-base<2.11,>=2.10.8->ansible->pyats.contrib) (3.3.1)
Requirement already satisfied: packaging in /Users/ragu/Desktop/ISE/prod/fullstack/iseapp/iseappstack/pyats_dev/lib/python3.8/site-packages (from ansible-base<2.11,>=2.10.8->ansible->pyats.contrib) (20.9)
Requirement already satisfied: six>=1.4.1 in /Users/ragu/Desktop/ISE/prod/fullstack/iseapp/iseappstack/pyats_dev/lib/python3.8/site-packages (from cryptography->ansible-base<2.11,>=2.10.8->ansible->pyats.contrib) (1.15.0)
Requirement already satisfied: cffi>=1.12 in /Users/ragu/Desktop/ISE/prod/fullstack/iseapp/iseappstack/pyats_dev/lib/python3.8/site-packages (from cryptography->ansible-base<2.11,>=2.10.8->ansible->pyats.contrib) (1.14.5)
Requirement already satisfied: pycparser in /Users/ragu/Desktop/ISE/prod/fullstack/iseapp/iseappstack/pyats_dev/lib/python3.8/site-packages (from cffi>=1.12->cryptography->ansible-base<2.11,>=2.10.8->ansible->pyats.contrib) (2.20)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/ragu/Desktop/ISE/prod/fullstack/iseapp/iseappstack/pyats_dev/lib/python3.8/site-packages (from jinja2->ansible-base<2.11,>=2.10.8->ansible->pyats.contrib) (1.1.1)
Requirement already satisfied: pyparsing>=2.0.2 in /Users/ragu/Desktop/ISE/prod/fullstack/iseapp/iseappstack/pyats_dev/lib/python3.8/site-packages (from packaging->ansible-base<2.11,>=2.10.8->ansible->pyats.contrib) (2.4.7)
Requirement already satisfied: idna<3,>=2.5 in /Users/ragu/Desktop/ISE/prod/fullstack/iseapp/iseappstack/pyats_dev/lib/python3.8/site-packages (from requests->pyats.contrib) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/ragu/Desktop/ISE/prod/fullstack/iseapp/iseappstack/pyats_dev/lib/python3.8/site-packages (from requests->pyats.contrib) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/ragu/Desktop/ISE/prod/fullstack/iseapp/iseappstack/pyats_dev/lib/python3.8/site-packages (from requests->pyats.contrib) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in /Users/ragu/Desktop/ISE/prod/fullstack/iseapp/iseappstack/pyats_dev/lib/python3.8/site-packages (from requests->pyats.contrib) (3.0.4)
Installing collected packages: pyats.contrib
Successfully installed pyats.contrib-21.4
**(pyats_dev) ragu@ragu-M-V132 yaml % pyats create testbed interactive --output test.yaml --encode-password

please make sure pyats.contrib is installed. If not, please do 'pip install pyats.contrib'.

invalid option: interactive**

(pyats_dev) ragu@ragu-M-V132 yaml % 
**(pyats_dev) ragu@ragu-M-V132 yaml % pyats create testbed Sample.xls --output testsample1.yaml -v        
Traceback (most recent call last):
  File "src/pyats/cli/base.py", line 207, in pyats.cli.base.Command.main
  File "src/pyats/cli/base.py", line 337, in pyats.cli.base.CommandWithSubcommands.run
  File "src/genie/cli/commands/create_testbed.py", line 43, in genie.cli.commands.create_testbed.CreateTestbed.run
Exception: please make sure pyats.contrib is installed. If not, please do 'pip install pyats.contrib'.

invalid option: Sample.xls**


please make sure pyats.contrib is installed. If not, please do 'pip install pyats.contrib'.

invalid option: Sample.xls

(pyats_dev) ragu@ragu-M-V132 yaml % pyats create testbed Sample.xls --output my_testbed.yaml

please make sure pyats.contrib is installed. If not, please do 'pip install pyats.contrib'.

invalid option: Sample.xls

(pyats_dev) ragu@ragu-M-V132 yaml % 





##################################################

(pyats_dev) ragu@ragu-M-V132 yaml % pyats version check
You are currently running pyATS version: 21.1
Python: 3.8.6 [64bit]

  Package                      Version
  ---------------------------- -------
  genie                        21.1.2 
  genie.libs.clean             21.1   
  genie.libs.conf              21.1   
  genie.libs.filetransferutils 21.1   
  genie.libs.health            21.1   
  genie.libs.ops               21.1   
  genie.libs.parser            21.1   
  genie.libs.sdk               21.1.2 
  pyats                        21.1   
  pyats.aereport               21.1   
  pyats.aetest                 21.1   
  pyats.async                  21.1   
  pyats.connections            21.1   
  pyats.datastructures         21.1   
  pyats.easypy                 21.1   
  pyats.kleenex                21.1   
  pyats.log                    21.1   
  pyats.reporter               21.1   
  pyats.results                21.1   
  pyats.tcl                    21.1   
  pyats.topology               21.1   
  pyats.utils                  21.1.2 
  unicon                       21.1   
  unicon.plugins               21.1   


(pyats_dev) ragu@ragu-M-V132 yaml % python -V
Python 3.8.6
(pyats_dev) ragu@ragu-M-V132 yaml % pip list
Package                      Version
---------------------------- -----------
aiofiles                     0.6.0
aiohttp                      3.7.2
aiohttp-swagger              1.0.15
ansible                      3.3.0
ansible-base                 2.10.8
appnope                      0.1.2
argon2-cffi                  20.1.0
arrow                        1.1.0
async-generator              1.10
async-lru                    1.0.2
async-timeout                3.0.1
attrs                        20.3.0
backcall                     0.2.0
backports.ssl                0.0.9
bcrypt                       3.2.0
binaryornot                  0.4.4
bleach                       3.3.0
certifi                      2020.12.5
cffi                         1.14.5
chardet                      3.0.4
click                        7.1.2
cookiecutter                 1.7.2
cryptography                 3.3.1
decorator                    5.0.7
defusedxml                   0.7.1
dill                         0.3.3
distro                       1.5.0
entrypoints                  0.3
genie                        20.10
genie.libs.clean             20.10.1
genie.libs.conf              20.10
genie.libs.filetransferutils 20.10
genie.libs.health            20.10.1
genie.libs.ops               20.10
genie.libs.parser            20.10
genie.libs.sdk               20.10
idna                         2.10
ipykernel                    5.5.3
ipython                      7.23.0
ipython-genutils             0.2.0
IxNetwork                    9.0.1915.16
jedi                         0.18.0
Jinja2                       2.11.3
jinja2-time                  0.2.0
jsonpickle                   2.0.0
jsonschema                   3.2.0
junit-xml                    1.9
jupyter-client               6.1.12
jupyter-core                 4.7.1
jupyterlab-pygments          0.1.2
MarkupSafe                   1.1.1
matplotlib-inline            0.1.2
mistune                      0.8.4
multidict                    5.1.0
nbclient                     0.5.3
nbconvert                    6.0.7
nbformat                     5.1.3
nest-asyncio                 1.5.1
netaddr                      0.8.0
notebook                     6.3.0
packaging                    20.9
pandocfilters                1.4.3
paramiko                     2.7.2
parso                        0.8.2
pathspec                     0.8.1
pexpect                      4.8.0
pickleshare                  0.7.5
pip                          21.1.1
ply                          3.11
poyo                         0.5.0
prettytable                  2.1.0
prometheus-client            0.10.1
prompt-toolkit               3.0.18
psutil                       5.8.0
ptyprocess                   0.7.0
pyasn1                       0.4.8
pyats                        20.10
pyats.aereport               20.10
pyats.aetest                 20.10
pyats.async                  20.10
pyats.connections            20.10
pyats.contrib                21.4
pyats.datastructures         20.10
pyats.easypy                 20.10.1
pyats.kleenex                20.10
pyats.log                    20.10.1
pyats.reporter               20.10
pyats.results                20.10
pyats.tcl                    20.10
pyats.topology               20.10
pyats.utils                  20.10
pycparser                    2.20
pycryptodomex                3.10.1
pyftpdlib                    1.5.6
Pygments                     2.9.0
PyNaCl                       1.4.0
pyOpenSSL                    20.0.1
pyparsing                    2.4.7
pyrsistent                   0.17.3
pysmi                        0.3.4
pysnmp                       4.4.12
python-dateutil              2.8.1
python-engineio              3.13.2
python-slugify               5.0.0
python-socketio              4.6.0
PyYAML                       5.4.1
pyzmq                        22.0.3
requests                     2.25.1
robotframework               3.2.2
ruamel.yaml                  0.17.4
ruamel.yaml.clib             0.2.2
Send2Trash                   1.5.0
setuptools                   56.0.0
six                          1.15.0
sshtunnel                    0.4.0
terminado                    0.9.4
testpath                     0.4.4
text-unidecode               1.3
tftpy                        0.8.0
tornado                      6.1
tqdm                         4.60.0
traitlets                    5.0.5
typing-extensions            3.10.0.0
unicon                       20.10
unicon.plugins               20.10
urllib3                      1.26.4
wcwidth                      0.2.5
webencodings                 0.5.1
websocket-client             0.58.0
wheel                        0.36.2
xlrd                         1.2.0
XlsxWriter                   1.4.0
xlwt                         1.3.0
xmltodict                    0.12.0
yamllint                     1.26.1
yarl                         1.6.3
(pyats_dev) ragu@ragu-M-V132 yaml %

**Comment by LukasMcClelland** [comment]
There seems to be a fair amount of version mismatching going on, so I'm guessing that this issue is likely due to package version mismatch. Please try running `pyats version update` and let me know if that solves the issue.

If you are unable to update, you could also try `pip install pyats.contrib==20.10` or `pip install pyats.contrib==21.1`

**Comment by ragu2k8** [comment]
No luck @LukasMcClelland i tried updating pyats and also tried both versions pyats.contrib==21.1 and pyats.contrib==20.10 but nothing helped getting same error
```

(pyats_dev) ragu@ragu-M-V132 yaml % pyats create testbed Sample.xls --output my_testbed1.yaml

please make sure pyats.contrib is installed. If not, please do 'pip install pyats.contrib'.

invalid option: Sample.xls
```

**Comment by LukasMcClelland** [comment]
Try this 
```
pyats create testbed file --path Sample.xls --output my_testbed1.yaml
```

**Comment by LukasMcClelland** [comment]
The error message could be improved to be more accurate here

**Comment by ragu2k8** [comment]
@LukasMcClelland `pyats create testbed file --path Sample.xls --output my_testbed1.yaml

please make sure pyats.contrib is installed. If not, please do 'pip install pyats.contrib'.

invalid option: file
`

**Comment by LukasMcClelland** [comment]
My apologies, I missed an equals sign. Please try:
```
pyats create testbed file --path=Sample.xls --output my_testbed1.yaml
```
